import { TrekData } from '../Expeditions/ExpeditionPage';

export const treks: Record<string, TrekData> = {

  'annapurna-base-camp-trek': {
    title: 'Annapurna Base Camp Trek',
    duration: '10–12 Days',
    difficulty: 'Moderate',
    elevation: '4,130 m / 13,550 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/annapurna-base-camp.jpg', '/assets/images/annapurna-sanctuary.jpg', '/assets/images/machhapuchhre.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Annapurna Base Camp Trek', href: '#' },
    ],
    description: `A soul-stirring journey into the heart of the Annapurna Sanctuary, where the world's 10th highest peak towers above a natural amphitheater of ice and snow. The Annapurna Base Camp Trek is one of Nepal's most rewarding journeys, combining lush rhododendron forests, traditional Gurung villages, and breathtaking high-alpine scenery.`,
    highlights: [
      'Stand at Annapurna Base Camp (4,130m) surrounded by a 360° amphitheater of Himalayan giants',
      'Sacred Machhapuchhre (Fishtail Peak) — the holy mountain never summited',
      'Classic Poon Hill sunrise over the Dhaulagiri and Annapurna ranges',
      'Trek through some of Nepal\'s finest rhododendron forests',
      'Warm Gurung village hospitality along the trail',
      'Natural hot springs at Jhinu Danda after descent',
      'Diverse landscapes from subtropical forests to high alpine snow',
    ],
    overview: [
      `The Annapurna Base Camp (ABC) trek is a moderate yet rewarding high-altitude journey into the natural amphitheater of the Annapurna Sanctuary. The trek begins with a drive to Pokhara and ascends through lush Modi Khola valley, passing traditional Gurung villages and dense rhododendron forests before reaching the iconic base camp at 4,130m, encircled by Annapurna I, Annapurna South, Hiunchuli, and the sacred Machhapuchhre.`,
      `The itinerary includes acclimatization days and strategic rest points, making it accessible to fit trekkers without technical mountaineering experience. The best seasons are spring (March–May) and autumn (September–November), when skies are clear and trails are at their best.`,
      `The trek is more than a physical journey — it's a cultural immersion through Gurung and Magar communities, ancient monasteries, and landscapes that shift dramatically from tropical lowlands to pristine alpine glaciers. The optional Poon Hill sunrise extension adds one of Nepal's most iconic viewpoints to the experience.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early and booking international flights with buffer days.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Drive to Pokhara (900 m)',                                          description: '7–8 hours by tourist bus. Overnight at hotel.' },
      { day: 3,  title: 'Drive to Nayapul & Trek to Tikhedhunga (1,540 m)',                  description: '1.5 hours drive then 3–4 hours trekking.' },
      { day: 4,  title: 'Trek to Ghorepani (2,840 m)',                                       description: '5–6 hours through rhododendron forests.' },
      { day: 5,  title: 'Poon Hill Sunrise (3,210 m) & Trek to Chomrong (2,170 m)',          description: 'Early sunrise hike then 6–7 hours trekking.' },
      { day: 6,  title: 'Trek to Bamboo (2,310 m)',                                          description: '5–6 hours through bamboo and rhododendron forests.' },
      { day: 7,  title: 'Trek to Deurali (3,230 m)',                                         description: '5–6 hours. Entering the upper sanctuary.' },
      { day: 8,  title: 'Trek to Annapurna Base Camp (4,130 m)',                             description: '5–6 hours. Standing at the heart of the Annapurna Sanctuary.' },
      { day: 9,  title: 'Trek to Bamboo (2,310 m)',                                          description: '6–7 hours descending. Hot springs at Jhinu Danda if time allows.' },
      { day: 10, title: 'Trek to Nayapul & Drive to Pokhara',                               description: '4–5 hours trekking then drive to Pokhara.' },
      { day: 11, title: 'Drive to Kathmandu',                                                description: '7–8 hours by tourist bus.' },
      { day: 12, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],
    included: [
      'All essential permits including ACAP and TIMS card',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu and Pokhara',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials including documents, water, camera, and sunscreen.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Annapurna',
  },

  'gokyo-lake-trek': {
    title: 'Gokyo Lake Trek',
    duration: '14 Days',
    difficulty: 'Moderate / Challenging',
    elevation: '5,483 m / 17,988 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/gokyo-lakes.jpg', '/assets/images/gokyo-ri.jpg', '/assets/images/ngozumpa-glacier.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Gokyo Lake Trek', href: '#' },
    ],
    description: `A spectacular journey to the turquoise jewels of the Himalayas, the Gokyo Lakes, culminating in a panoramic sunrise vista of Mount Everest and four other 8,000-meter giants from the summit of Gokyo Ri. This stunning, less-traveled alternative to the main EBC route offers unparalleled pristine beauty.`,
    highlights: [
      'Gokyo Ri summit (5,483m) — panoramic views of Everest, Lhotse, Makalu, and Cho Oyu',
      'Pristine turquoise Gokyo Lakes — among Nepal\'s most beautiful high-altitude lakes',
      'The massive Ngozumpa Glacier — the largest glacier in Nepal',
      'Sherpa culture immersion in Namche Bazaar',
      'View from Everest View Hotel on acclimatization day',
      'Optional Renjo La Pass crossing for extended adventure',
      'Quieter trails away from the main EBC corridor',
    ],
    overview: [
      `The Gokyo Lake Trek is a moderately difficult, high-altitude journey distinguished by its spectacular scenery. Starting with a flight to Lukla (2,840m), the trail ascends gradually over 14 days with crucial acclimatization stops built in, notably at Namche Bazaar. The highest point and primary reward is the summit of Gokyo Ri (5,483m), which offers a breathtaking panorama of Everest, Lhotse, Makalu, and Cho Oyu.`,
      `Success on this trek hinges on respecting the altitude. Trekkers must be prepared for the risks of Acute Mountain Sickness (AMS), especially as the itinerary involves significant elevation gains to the Gokyo Lakes region (4,800m). A slow, steady pace, thorough hydration, and avoiding alcohol are critical safety precautions.`,
      `The trek culminates at Gokyo Village (4,800m), nestled beside the pristine Third Lake, with the vast Ngozumpa Glacier as its dramatic backdrop. This is a deep connection with the colossal power of the world's highest mountains and the resilient Buddhist culture of the Sherpa people.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early and booking international flights with buffer days.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,350 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner at a traditional Nepali restaurant.' },
      { day: 3,  title: 'Fly to Lukla (2,860 m) & Trek to Phakding (2,610 m)',              description: '3–4 hours trekking after scenic mountain flight.' },
      { day: 4,  title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '5–6 hours through forests and suspension bridges.' },
      { day: 5,  title: 'Acclimatization Day at Namche Bazaar',                             description: 'Hike to Everest View Hotel (3,880m) for first views of Everest, Lhotse, and Ama Dablam.' },
      { day: 6,  title: 'Trek to Dole (4,038 m)',                                            description: '5–7 hours. Trail diverges from EBC route toward Gokyo Valley.' },
      { day: 7,  title: 'Trek to Machhermo (4,470 m)',                                       description: '4–5 hours. Enjoy views of the massive Cho Oyu peak.' },
      { day: 8,  title: 'Trek to Gokyo Village / Third Lake (4,790 m)',                      description: '4–5 hours. Arrive at the main Gokyo Lake.' },
      { day: 9,  title: 'Summit Gokyo Ri (5,483 m) & Explore 4th and 5th Lakes',            description: '5–6 hours round trip for panoramic sunrise views.' },
      { day: 10, title: 'Trek to Dole (4,038 m)',                                            description: '5–6 hours. Begin descent, retracing the valley path.' },
      { day: 11, title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '4–5 hours.' },
      { day: 12, title: 'Trek to Lukla (2,860 m)',                                           description: '6–8 hours. Final trekking day.' },
      { day: 13, title: 'Fly to Kathmandu',                                                  description: 'Early morning flight back. Farewell dinner celebration.' },
      { day: 14, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],
    included: [
      'All essential permits including Sagarmatha National Park and Khumbu local permit',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials including documents, water, camera, and sunscreen.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Gokyo',
  },

  'annapurna-circuit-trek': {
    title: 'Annapurna Circuit Trek',
    duration: '16 Days',
    difficulty: 'Strenuous / Challenging',
    elevation: '5,416 m / 17,769 ft',
    season: 'Feb–May & Sep–Dec',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/annapurna-circuit.jpg', '/assets/images/thorung-la.jpg', '/assets/images/manang-valley.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Annapurna Circuit Trek', href: '#' },
    ],
    description: `An exhilarating odyssey through diverse landscapes to the awe-inspiring Annapurna giants — a legendary journey that physically circumnavigates the colossal Annapurna Mountain range. The circuit offers an experience that changes dramatically day by day, from subtropical lowlands to the wind-swept heights of Thorung La Pass.`,
    highlights: [
      'Cross Thorung La Pass (5,416m) — the world\'s most famous high-altitude mountain pass',
      'Hot springs at Tatopani — a perfect reward after the pass crossing',
      'Panoramic Himalayan views of Annapurna, Dhaulagiri, and Manaslu',
      'Manang Valley — dramatic Tibetan plateau landscapes',
      'The pilgrimage town of Muktinath with 108 sacred water spouts',
      'Charming villages and authentic local culture throughout',
      'Apple orchards and local cuisine in Marpha',
      'Marsyangdi River Valley gorges and suspension bridges',
    ],
    overview: [
      `The Annapurna Circuit Trek is a legendary journey through the diverse terrain of the Nepalese Himalayas. Starting in the lower warmer regions, characterized by lush terraced hillsides and vibrant rice paddies, the route gradually transitions through pine and rhododendron forests to cooler temperate zones, then into an arid desert-like plateau with ancient monasteries, chortens, and prayer flags.`,
      `The trek demands good physical fitness and a disciplined approach to acclimatization. The route is dotted with teahouses providing basic but comfortable accommodation and meals. The overall experience is one of continuous change — in scenery, climate, vegetation, and local culture.`,
      `The dramatic climax comes at Thorung La Pass (5,416m), where trekkers are rewarded with breathtaking panoramas stretching from the Manaslu range to the immense Dhaulagiri Massif. The descent into the sacred valley of Muktinath and the apple town of Marpha rounds out one of the world's truly great trekking circuits.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early and booking international flights with buffer days.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Sightseeing, gear check, and welcome dinner.' },
      { day: 3,  title: 'Drive from Kathmandu to Chamje (1,410 m)',                          description: 'Scenic drive following the Trishuli and Marsyangdi Rivers.' },
      { day: 4,  title: 'Trek from Chamje to Dharapani (1,960 m)',                           description: '5–6 hours. Trail passes traditional villages and waterfalls.' },
      { day: 5,  title: 'Trek from Dharapani to Chame (2,670 m)',                            description: '5–6 hours through dense forests of pine and fir.' },
      { day: 6,  title: 'Trek from Chame to Upper Pisang (3,300 m)',                         description: '5–6 hours. Pass the dramatic Paungda Danda rock face.' },
      { day: 7,  title: 'Trek from Upper Pisang to Manang (3,540 m)',                        description: '5–6 hours via the upper trail through Ghyaru and Ngawal.' },
      { day: 8,  title: 'Acclimatization Day in Manang (3,540 m)',                           description: 'Rest and short hikes for acclimatization.' },
      { day: 9,  title: 'Trek from Manang to Yak Kharka (4,050 m)',                          description: '4–5 hours through increasingly alpine terrain.' },
      { day: 10, title: 'Trek from Yak Kharka to Thorong Phedi (4,450 m)',                   description: '3–4 hours. Final overnight before the pass.' },
      { day: 11, title: 'Cross Thorung La Pass (5,416 m) & Descend to Muktinath (3,760 m)', description: '7–8 hours. The legendary pass crossing.' },
      { day: 12, title: 'Trek from Muktinath to Marpha (2,670 m)',                           description: '5–6 hours. Visit the apple capital of Nepal.' },
      { day: 13, title: 'Trek from Marpha to Tatopani (1,190 m)',                            description: '6–7 hours. Soak in the famous hot springs.' },
      { day: 14, title: 'Trek from Tatopani to Ghorepani (2,840 m)',                         description: '6–7 hours through rhododendron forests.' },
      { day: 15, title: 'Poon Hill Sunrise (3,210 m) & Drive to Pokhara',                   description: 'Early sunrise hike, then drive back to Pokhara.' },
      { day: 16, title: 'Drive to Kathmandu & Departure',                                    description: '7–8 hours by tourist bus. Airport transfer.' },
    ],
    included: [
      'All essential permits including ACAP permit and TIMS card',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu and Pokhara',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials including documents, water, camera, and sunscreen.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'the Circuit',
  },

  'upper-mustang-trek': {
    title: 'Upper Mustang Trek',
    duration: '17 Days',
    difficulty: 'Moderate',
    elevation: '3,840 m / 12,598 ft (Lo Manthang)',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/mustang-region.jpg', '/assets/images/lo-manthang.jpg', '/assets/images/upper-mustang.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Upper Mustang Trek', href: '#' },
    ],
    description: `A journey into Nepal's forbidden kingdom — a lunar landscape of ochre cliffs, ancient cave monasteries, and Tibetan Buddhist culture frozen in time. Upper Mustang is one of the last Himalayan rain-shadow deserts, offering a unique trekking experience in a region that remained closed to outsiders until 1992.`,
    highlights: [
      'Lo Manthang — the walled capital of the ancient Kingdom of Lo',
      'Dramatic Tibetan plateau landscapes of ochre, red, and brown',
      'Ancient cave monasteries carved into cliffsides',
      'Rain-shadow desert trekking — viable even in monsoon season',
      'Rare Tibetan Buddhist art and cultural heritage',
      'Stunning views of Nilgiri, Tilicho, and Dhaulagiri',
      'Restricted area permit experience in Nepal\'s most exclusive trekking zone',
    ],
    overview: [
      `The Upper Mustang Trek is a unique high-altitude journey into one of the world's most dramatic rain-shadow deserts. Protected as a restricted area requiring special permits, Upper Mustang retains a Tibetan culture largely untouched by modernization, offering trekkers a rare window into a living medieval Himalayan kingdom.`,
      `The trek typically begins with a scenic flight from Pokhara to Jomsom, then follows the ancient salt-trade route north through the Kali Gandaki gorge into the forbidden kingdom. The terrain is unlike anywhere else in Nepal — arid, wind-sculpted canyons, ancient cave dwellings, and flat-roofed villages against a backdrop of impossibly blue skies.`,
      `The highlight is Lo Manthang, the walled capital city of the ancient Kingdom of Lo, where the Lo-pa king's palace, ancient monasteries, and traditional culture remain remarkably intact. This is a trek for those seeking genuine cultural discovery and otherworldly landscapes.`,
      `NOTE: Upper Mustang requires a special Restricted Area Permit in addition to the ACAP permit, and a licensed guide is mandatory. We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Permit processing, gear check, and welcome dinner.' },
      { day: 3,  title: 'Drive to Pokhara (900 m)',                                          description: '7–8 hours by tourist bus. Overnight at hotel.' },
      { day: 4,  title: 'Fly Pokhara to Jomsom (2,720 m) & Trek to Kagbeni (2,810 m)',      description: '30-minute scenic flight then 2–3 hours trekking.' },
      { day: 5,  title: 'Trek to Chele (3,050 m)',                                           description: '5–6 hours. Enter the restricted Upper Mustang zone.' },
      { day: 6,  title: 'Trek to Syangboche (3,800 m)',                                      description: '6–7 hours through dramatic canyon landscapes.' },
      { day: 7,  title: 'Trek to Ghami (3,520 m)',                                           description: '5–6 hours via Nyi La Pass (4,010m).' },
      { day: 8,  title: 'Trek to Charang (3,560 m)',                                         description: '5–6 hours. Visit the Charang monastery.' },
      { day: 9,  title: 'Trek to Lo Manthang (3,840 m)',                                     description: '5–6 hours. Enter the walled capital of the Kingdom of Lo.' },
      { day: 10, title: 'Exploration Day in Lo Manthang',                                    description: 'Visit the palace, Thubchen Gompa, Jampa Gompa, and surrounding caves.' },
      { day: 11, title: 'Trek to Drakmar (3,810 m) via Ghar Gompa',                         description: '5–6 hours. Visit the 13th-century Ghar Gompa.' },
      { day: 12, title: 'Trek to Ghami (3,520 m)',                                           description: '5–6 hours on the return route.' },
      { day: 13, title: 'Trek to Tangbe (3,060 m)',                                          description: '6–7 hours.' },
      { day: 14, title: 'Trek to Kagbeni (2,810 m)',                                         description: '4–5 hours. Back to the gateway village.' },
      { day: 15, title: 'Trek to Jomsom (2,720 m)',                                          description: '3–4 hours. Final trekking day.' },
      { day: 16, title: 'Fly Jomsom to Pokhara & Drive to Kathmandu',                       description: '30-minute flight then 7–8 hours drive.' },
      { day: 17, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],
    included: [
      'All essential permits including Upper Mustang Restricted Area Permit and ACAP permit',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu and Pokhara',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'Flights Pokhara–Jomsom–Pokhara',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'A licensed guide is mandatory for Upper Mustang — solo trekking is not permitted.',
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials including documents, water, camera, and sunscreen.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Mustang',
  },

  'langtang-valley-trek': {
    title: 'Langtang Valley Trek',
    duration: '12 Days',
    difficulty: 'Moderate',
    elevation: '3,830 m / 12,566 ft (Kyanjin Gompa)',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/langtang-valley.jpg', '/assets/images/kyanjin-gompa.jpg', '/assets/images/langtang-lirung.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Langtang Valley Trek', href: '#' },
    ],
    description: `A beautiful valley trek just north of Kathmandu, through resilient Tamang villages and yak pastures to the ancient Kyanjin Gompa monastery, with breathtaking views of Langtang Lirung (7,227m). One of Nepal's most accessible yet spectacular trekking destinations.`,
    highlights: [
      'Kyanjin Gompa (3,830m) — one of Nepal\'s most beautiful high-altitude monasteries',
      'Views of Langtang Lirung (7,227m) directly from the valley floor',
      'Optional Tserko Ri hike (4,984m) for spectacular panoramas',
      'Authentic Tamang culture and warm village hospitality',
      'Visit the famous Kyanjin yak cheese factory',
      'Langtang National Park — rich biodiversity and forest scenery',
      'Closest major trek to Kathmandu — minimal travel time',
    ],
    overview: [
      `The Langtang Valley Trek is a beautiful moderate-difficulty journey just north of Kathmandu into the Langtang National Park. Starting with a scenic drive to Syabrubesi, the trail winds through dense forests of oak, rhododendron, and bamboo, ascending to the wide open alpine pastures of Langtang Valley beneath the towering Langtang Lirung massif.`,
      `The trek showcases the warm Tamang culture of the region, with traditional stone villages, prayer flags, and mani walls lining the trail. The highlight is Kyanjin Gompa at 3,830m, where an ancient monastery, a famous yak cheese factory, and the option to climb Tserko Ri for 360° Himalayan views make for a memorable destination.`,
      `The valley has dramatically recovered since the 2015 earthquake and today offers a deeply moving experience of Himalayan resilience alongside world-class scenery. Being the closest major trek to Kathmandu, it requires minimal travel time and is an ideal choice for those with limited days.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner at a traditional Nepali restaurant.' },
      { day: 3,  title: 'Drive to Syabru Besi (1,462 m)',                                    description: '7–8 hours through scenic mountain roads.' },
      { day: 4,  title: 'Trek to Lama Hotel (2,500 m)',                                      description: '5–6 hours through dense forest.' },
      { day: 5,  title: 'Trek to Langtang Village (3,430 m)',                                description: '5–6 hours. Trail opens to wide alpine meadows.' },
      { day: 6,  title: 'Trek to Kyanjin Gompa (3,830 m)',                                   description: '4–5 hours to the spiritual heart of the Langtang region.' },
      { day: 7,  title: 'Exploration Day at Kyanjin Gompa',                                 description: 'Optional hike to Tserko Ri (4,984m). Visit the yak cheese factory and monastery.' },
      { day: 8,  title: 'Trek Back to Lama Hotel (2,500 m)',                                 description: '5–6 hours descending the valley.' },
      { day: 9,  title: 'Trek to Syabru Besi (1,462 m)',                                     description: '5–6 hours. Final trekking day.' },
      { day: 10, title: 'Drive Back to Kathmandu',                                           description: '7–8 hours. Overnight at hotel.' },
      { day: 11, title: 'Free Day in Kathmandu / Optional Sightseeing',                     description: 'Rest or optional cultural exploration.' },
      { day: 12, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],
    included: [
      'All essential permits including Langtang National Park entry permit and TIMS card',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Langtang',
  },

  'ghorepani-poon-hill-trek': {
    title: 'Ghorepani Poon Hill Trek',
    duration: '9 Days',
    difficulty: 'Moderate',
    elevation: '3,210 m / 10,531 ft (Poon Hill)',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/poon-hill.jpg', '/assets/images/ghorepani.jpg', '/assets/images/annapurna-sunrise.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Ghorepani Poon Hill Trek', href: '#' },
    ],
    description: `Nepal's most iconic sunrise viewpoint, where the golden light ignites Dhaulagiri, Annapurna, and Machhapuchhre in a panorama that has inspired trekkers for generations. The perfect short trek combining Gurung culture, rhododendron forests, and world-class Himalayan views.`,
    highlights: [
      'Poon Hill sunrise (3,210m) — arguably Nepal\'s most famous sunrise viewpoint',
      'Panoramic views of Dhaulagiri, Annapurna South, Nilgiri, and Machhapuchhre',
      'World-class rhododendron forests in full bloom (March–April)',
      'Authentic Magar and Gurung village culture',
      'Short, accessible trek ideal for beginners and families',
      'Charming teahouse hospitality throughout',
      'Optional extension to Annapurna Base Camp',
    ],
    overview: [
      `The Ghorepani Poon Hill Trek is Nepal's most popular short trek, combining accessible terrain with world-class Himalayan scenery. Starting from Nayapul near Pokhara, the trail winds through traditional Magar and Gurung villages, dense rhododendron and oak forests, to the ridge village of Ghorepani and the iconic Poon Hill viewpoint.`,
      `The pre-dawn hike to Poon Hill (3,210m) rewards trekkers with one of the Himalayas' most celebrated sunrise panoramas, stretching across Dhaulagiri (8,167m), Annapurna I (8,091m), Annapurna South, Nilgiri, and the sacred Machhapuchhre. The sight of golden light igniting these peaks against the dark sky is an experience that stays with trekkers for life.`,
      `The trek is well-suited for beginners, families, and those with limited time. The trail is well-maintained, teahouses are plentiful, and the maximum elevation is manageable even for first-time trekkers. Spring (March–April) brings the rhododendron forests into spectacular full bloom, adding vibrant pink and red color to the landscape.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Drive to Pokhara (900 m)',                                          description: '7–8 hours by tourist bus. Overnight at hotel.' },
      { day: 3,  title: 'Drive to Nayapul & Trek to Tikhedhunga (1,540 m)',                  description: '1.5 hours drive then 3–4 hours trekking.' },
      { day: 4,  title: 'Trek to Ghorepani (2,840 m)',                                       description: '5–6 hours through spectacular rhododendron forests.' },
      { day: 5,  title: 'Poon Hill Sunrise (3,210 m) & Trek to Tadapani (2,630 m)',          description: 'Pre-dawn summit hike then 4–5 hours trekking.' },
      { day: 6,  title: 'Trek to Chomrong (2,170 m)',                                        description: '5–6 hours through Gurung villages.' },
      { day: 7,  title: 'Trek to Jhinu Danda (1,780 m) & Hot Springs',                      description: '3–4 hours trekking. Relax at natural hot springs.' },
      { day: 8,  title: 'Trek to Nayapul & Drive to Pokhara',                               description: '3–4 hours trekking then drive to Pokhara.' },
      { day: 9,  title: 'Drive to Kathmandu & Departure',                                    description: '7–8 hours by tourist bus. Airport transfer.' },
    ],
    included: [
      'All essential permits including ACAP and TIMS card',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu and Pokhara',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Poon Hill',
  },

  'everest-three-passes-trek': {
    title: 'Everest Three Passes Trek',
    duration: '21 Days',
    difficulty: 'Strenuous',
    elevation: '5,535 m / 18,159 ft (Kongma La)',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/everest-base-camp.jpg', '/assets/images/gokyo-lakes.jpg', '/assets/images/cho-la-pass.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Everest Three Passes Trek', href: '#' },
    ],
    description: `The ultimate Khumbu Grand Slam — conquering three legendary high passes (Kongma La, Cho La, and Renjo La) while visiting Everest Base Camp, Gokyo Lakes, and Kala Patthar for the most complete Everest region experience possible. A true test of endurance and commitment.`,
    highlights: [
      'Cross all three legendary passes: Kongma La (5,535m), Cho La (5,420m), and Renjo La (5,340m)',
      'Stand at Everest Base Camp (5,364m)',
      'Kala Patthar (5,545m) sunrise — the iconic Everest viewpoint',
      'Gokyo Ri panorama of four 8,000m peaks',
      'Pristine turquoise Gokyo Lakes',
      'The vast Ngozumpa Glacier — Nepal\'s largest',
      'Deep immersion in Sherpa culture and Khumbu wilderness',
    ],
    overview: [
      `The Everest Three Passes Trek is the most comprehensive trekking itinerary in the Khumbu region, demanding exceptional endurance and sustained high-altitude commitment. Beginning with a flight to Lukla, the route ventures across all three major passes of the Everest region — Kongma La, Cho La, and Renjo La — while also taking in Everest Base Camp, Kala Patthar, and the Gokyo Valley.`,
      `Success on this trek requires peak physical conditioning and disciplined acclimatization. The itinerary spends sustained time above 4,000m and regularly approaches or exceeds 5,000m, making altitude management the highest priority. Each pass involves some technical terrain with possible snow and ice, and trekkers should be comfortable with steep, exposed sections.`,
      `The reward is unmatched: a complete, 360-degree experience of the Everest region that most trekkers never see. From the remote serenity of the Gokyo Valley to the dramatic base camp environment, from the sacred monasteries of Tengboche to the stark grandeur of the high passes — this trek represents the full spectrum of what the Khumbu has to offer.`,
      `NOTE: We strive to follow the planned itinerary, but weather or health conditions may require adjustments. We strongly recommend arriving one or two days early and booking international flights with buffer days.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner.' },
      { day: 3,  title: 'Fly to Lukla (2,840 m) & Trek to Phakding (2,610 m)',              description: '35-minute flight. Trek 3–4 hours.' },
      { day: 4,  title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '5–6 hours.' },
      { day: 5,  title: 'Acclimatization Day at Namche Bazaar',                             description: 'Hike to Everest View Hotel and back.' },
      { day: 6,  title: 'Trek to Dole (4,200 m)',                                            description: '6–7 hours toward the Gokyo Valley.' },
      { day: 7,  title: 'Trek to Machherma (4,470 m)',                                       description: '5–6 hours.' },
      { day: 8,  title: 'Trek to Gokyo (4,800 m)',                                           description: '5–6 hours.' },
      { day: 9,  title: 'Gokyo Ri (5,483 m) Summit & Explore Lakes',                        description: '5–6 hours round trip sunrise hike.' },
      { day: 10, title: 'Trek to Thangna (4,500 m)',                                         description: '4–5 hours toward Cho La.' },
      { day: 11, title: 'Cross Cho La Pass (5,420 m) & Trek to Dzongla (4,830 m)',          description: '7–8 hours crossing the pass.' },
      { day: 12, title: 'Trek to Lobuche (4,910 m)',                                         description: '4–5 hours.' },
      { day: 13, title: 'Trek to Gorak Shep & Kala Patthar (5,545 m)',                      description: 'Pre-dawn hike to Kala Patthar for Everest sunrise.' },
      { day: 14, title: 'Trek to Everest Base Camp (5,364 m) & Return to Lobuche',          description: '7–8 hours.' },
      { day: 15, title: 'Cross Kongma La Pass (5,535 m) & Trek to Chukhung (4,710 m)',      description: '8–9 hours crossing the highest pass.' },
      { day: 16, title: 'Trek to Tengboche Monastery (3,860 m)',                             description: '6–7 hours descending.' },
      { day: 17, title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '5–6 hours.' },
      { day: 18, title: 'Trek to Thame (3,800 m)',                                           description: '3–4 hours toward Renjo La.' },
      { day: 19, title: 'Cross Renjo La Pass (5,340 m) & Trek to Lunden (4,300 m)',         description: '7–8 hours crossing the third pass.' },
      { day: 20, title: 'Trek to Lukla (2,840 m)',                                           description: '6–7 hours. Final trekking day.' },
      { day: 21, title: 'Fly to Kathmandu & Departure',                                      description: '35-minute flight. Airport transfer.' },
    ],
    included: [
      'All essential permits including Sagarmatha National Park and Khumbu local permit',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Three Passes',
  },

  'mardi-himal-trek': {
    title: 'Mardi Himal Trek',
    duration: '11 Days',
    difficulty: 'Moderate',
    elevation: '4,500 m / 14,764 ft (High Camp)',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/mardi-himal.jpg', '/assets/images/mardi-high-camp.jpg', '/assets/images/machhapuchhre-base.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Mardi Himal Trek', href: '#' },
    ],
    description: `A hidden gem on the eastern ridge of the Annapurna Sanctuary — a less-traveled trail with intimate views of Machhapuchhre (Fishtail), Mardi Himal, and Annapurna South from spectacular high camps. The Mardi Himal Trek offers a genuine off-the-beaten-path experience in the heart of the Annapurna region.`,
    highlights: [
      'Intimate close-up views of Machhapuchhre (Fishtail) from High Camp (4,500m)',
      'Off-the-beaten-path trail with few other trekkers',
      'Panoramic views of Mardi Himal, Annapurna South, and Hiunchuli',
      'Forest Camp and Low Camp — peaceful overnight stays in the wilderness',
      'Gurung and Magar village culture along the lower trail',
      'Spectacular alpine scenery without the Annapurna Base Camp crowds',
    ],
    overview: [
      `The Mardi Himal Trek is a relatively new but increasingly popular route on the eastern ridge of the Annapurna Sanctuary. Starting from Pokhara, the trail winds through rhododendron forests, past Gurung and Magar villages, and gradually ascends to Forest Camp, Low Camp, and finally High Camp at 4,500m, where Machhapuchhre appears astonishingly close and personal.`,
      `Unlike the main Annapurna Base Camp trail, the Mardi Himal route remains quieter and less commercialized, offering a more intimate wilderness experience. The views at High Camp are among the most dramatic in the entire Annapurna region, with Machhapuchhre, Mardi Himal, and Annapurna South filling the horizon.`,
      `The trek is well-suited for moderate trekkers seeking something different from the classic Annapurna trails. The maximum elevation of 4,500m at High Camp makes acclimatization manageable, while the scenery and isolation rival any trek in Nepal.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Drive to Pokhara (900 m)',                                          description: '7–8 hours by tourist bus. Overnight at hotel.' },
      { day: 3,  title: 'Drive to Kande & Trek to Forest Camp (2,520 m)',                    description: '1 hour drive then 5–6 hours trekking.' },
      { day: 4,  title: 'Trek to Low Camp (3,150 m)',                                        description: '5–6 hours through rhododendron forests.' },
      { day: 5,  title: 'Trek to High Camp (4,500 m)',                                       description: '5–6 hours. First intimate views of Machhapuchhre.' },
      { day: 6,  title: 'Acclimatization & Viewpoint Hike at High Camp',                    description: 'Short exploration for panoramic morning views.' },
      { day: 7,  title: 'Trek to Siding Village (1,750 m)',                                  description: '6–7 hours descending through the lower valley.' },
      { day: 8,  title: 'Trek to Lumre & Drive to Pokhara',                                 description: '3–4 hours trekking then drive to Pokhara.' },
      { day: 9,  title: 'Free Day in Pokhara',                                               description: 'Rest, lakeside exploration, or optional activities.' },
      { day: 10, title: 'Drive to Kathmandu',                                                description: '7–8 hours by tourist bus.' },
      { day: 11, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],
    included: [
      'All essential permits including ACAP and TIMS card',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu and Pokhara',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Mardi Himal',
  },

  'nar-phu-valley-trek': {
    title: 'Nar Phu Valley Trek',
    duration: '16 Days',
    difficulty: 'Challenging',
    elevation: '5,320 m / 17,454 ft (Kang La Pass)',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/nar-phu-valley.jpg', '/assets/images/kang-la-pass.jpg', '/assets/images/manang.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Nar Phu Valley Trek', href: '#' },
    ],
    description: `One of Nepal's last truly remote trekking frontiers — a restricted area of ancient Tibetan villages, dramatic gorges, and high passes that connects the hidden Nar and Phu valleys to the Annapurna Circuit. This is Nepal trekking as it was 30 years ago.`,
    highlights: [
      'Nar and Phu — two of Nepal\'s most remote and authentic Tibetan-influenced villages',
      'Cross Kang La Pass (5,320m) for dramatic high-altitude views',
      'Restricted area permit experience — very few trekkers per year',
      'Ancient Buddhist monasteries, chortens, and mani walls',
      'Wildlife possibility: snow leopards, Himalayan tahr, and blue sheep',
      'Deep Annapurna gorge scenery in the lower valley',
      'Connect with the Annapurna Circuit at Koto for a combined adventure',
    ],
    overview: [
      `The Nar Phu Valley Trek is one of Nepal's most exclusive trekking experiences, requiring a special restricted area permit and a licensed guide. The valley branches off the Annapurna Circuit near Koto and ascends into a hidden world of ancient Tibetan settlements, dramatic cliffs, and high-altitude wilderness that sees very few visitors each year.`,
      `The villages of Phu and Nar are among the most authentically Tibetan communities in Nepal, with traditional architecture, ancient monasteries, and a way of life largely unchanged for centuries. The crossing of Kang La Pass (5,320m) connects the two valleys and offers breathtaking views of the surrounding peaks.`,
      `This trek is typically combined with the Annapurna Circuit for a comprehensive high-altitude adventure. The restricted area designation ensures the valley remains pristine and uncrowded, making it one of Nepal's most rewarding off-the-beaten-path destinations.`,
      `NOTE: A licensed guide is mandatory for this restricted area. We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Permit processing and welcome dinner.' },
      { day: 3,  title: 'Drive from Kathmandu to Koto (2,640 m)',                            description: '8–9 hours by private vehicle.' },
      { day: 4,  title: 'Trek to Meta (3,560 m)',                                             description: '5–6 hours entering the Nar Phu restricted zone.' },
      { day: 5,  title: 'Trek to Kyang (3,840 m)',                                           description: '5–6 hours through dramatic gorge scenery.' },
      { day: 6,  title: 'Trek to Phu Village (4,080 m)',                                     description: '5–6 hours. First authentic Tibetan settlement.' },
      { day: 7,  title: 'Exploration Day in Phu',                                            description: 'Visit Tashi Lhakhang Monastery and surroundings.' },
      { day: 8,  title: 'Trek to Nar Phedi (4,200 m)',                                       description: '5–6 hours through high alpine terrain.' },
      { day: 9,  title: 'Cross Kang La Pass (5,320 m) & Trek to Ngawal (3,657 m)',          description: '8–9 hours. The trek\'s dramatic high point.' },
      { day: 10, title: 'Trek to Manang (3,540 m)',                                          description: '4–5 hours. Join the Annapurna Circuit.' },
      { day: 11, title: 'Acclimatization Day at Manang',                                     description: 'Rest and short hikes for recovery.' },
      { day: 12, title: 'Trek to Yak Kharka (4,050 m)',                                      description: '4–5 hours toward Thorung La.' },
      { day: 13, title: 'Trek to Thorong Phedi (4,450 m)',                                   description: '3–4 hours. Final night before the pass.' },
      { day: 14, title: 'Cross Thorung La Pass (5,416 m) & Descend to Muktinath (3,760 m)', description: '7–8 hours. The legendary crossing.' },
      { day: 15, title: 'Drive from Muktinath to Pokhara',                                   description: 'Drive via Jomsom and Beni. Overnight at hotel.' },
      { day: 16, title: 'Drive to Kathmandu & Departure',                                    description: '7–8 hours. Airport transfer.' },
    ],
    included: [
      'All essential permits including Nar Phu Restricted Area Permit, ACAP, and TIMS card',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu and Pokhara',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'A licensed guide is mandatory for the Nar Phu restricted area — solo trekking is not permitted.',
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Nar Phu',
  },

  'langtang-heritage-trek': {
    title: 'Langtang Heritage Trek',
    duration: '16 Days',
    difficulty: 'Moderate',
    elevation: '4,610 m / 15,120 ft (Laurebinayak Pass)',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/langtang-heritage.jpg', '/assets/images/kyanjin-gompa.jpg', '/assets/images/gosainkunda.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Langtang Heritage Trek', href: '#' },
    ],
    description: `A cultural and natural odyssey through the three valleys of the Langtang region — combining the pristine Langtang Valley, the sacred Gosaikunda alpine lakes, and the verdant Helambu Valley in one immersive journey through traditional Tamang and Sherpa communities.`,
    highlights: [
      'Kyanjin Gompa — the spiritual heart of the Langtang region',
      'Sacred Gosaikunda Lake (4,380m) — a major Hindu and Buddhist pilgrimage site',
      'Cross Laurebinayak Pass (4,610m) for spectacular mountain views',
      'Helambu Valley — peaceful forested landscapes and Sherpa culture',
      'Diverse ecosystems from subtropical forest to alpine tundra',
      'Traditional Tamang and Sherpa village heritage',
      'Langtang National Park — forests, meadows, and alpine scenery',
    ],
    overview: [
      `The Langtang Heritage Trek is a unique Himalayan adventure combining the pristine Langtang Valley, the sacred Gosaikunda region, and the verdant Helambu Valley. This trek provides a perfect balance of cultural immersion, alpine scenery, high mountain passes, and forested landscapes.`,
      `Beginning with a drive from Kathmandu to Syabru Besi, trekkers ascend through lush forests, quaint villages, and traditional Tamang settlements into Langtang Valley. Highlights include Kyanjin Gompa, local cheese factories, and panoramic Himalayan views. The trek continues toward the sacred lakes of Gosaikunda before crossing the demanding Laurebinayak Pass.`,
      `Descending toward the Helambu Valley, trekkers experience rhododendron and pine forests, peaceful villages, and rich Sherpa and Tamang culture. The final stages lead back toward Melamchi Pul Bazaar, completing an immersive Himalayan journey that blends adventure, spirituality, and cultural discovery.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner.' },
      { day: 3,  title: 'Drive to Syabru Besi (1,503 m)',                                    description: '7–9 hours. Overnight at guesthouse.' },
      { day: 4,  title: 'Trek to Lama Hotel (2,500 m)',                                      description: '5–6 hours. Overnight at guesthouse.' },
      { day: 5,  title: 'Trek to Langtang Village (3,430 m)',                                description: '5–6 hours. Overnight at guesthouse.' },
      { day: 6,  title: 'Trek to Kyanjin Gompa (3,830 m)',                                   description: '4–5 hours. Overnight at guesthouse.' },
      { day: 7,  title: 'Exploration / Rest Day at Kyanjin Gompa',                          description: 'Optional Tserko Ri hike and monastery visit.' },
      { day: 8,  title: 'Trek Back to Lama Hotel (2,500 m)',                                 description: '5–6 hours descending.' },
      { day: 9,  title: 'Trek to Thulo Syabru (2,150 m)',                                    description: '5–6 hours. Overnight at guesthouse.' },
      { day: 10, title: 'Trek to Sing Gompa (3,330 m)',                                      description: '5–6 hours. Overnight at guesthouse.' },
      { day: 11, title: 'Trek to Gosaikunda Lake (4,380 m)',                                 description: '5–6 hours to the sacred alpine lake.' },
      { day: 12, title: 'Cross Laurebinayak Pass (4,610 m) & Trek to Ghopte (3,530 m)',     description: '6–7 hours. Demanding but rewarding high pass crossing.' },
      { day: 13, title: 'Trek to Melamchi Gaon via Tharepati Pass (2,530 m)',               description: '6–7 hours descending into Helambu.' },
      { day: 14, title: 'Trek to Tarkeghyang (2,600 m)',                                     description: '5–6 hours through Helambu Valley.' },
      { day: 15, title: 'Trek to Melamchi Pul Bazaar (870 m)',                               description: '5–6 hours. Final trekking day.' },
      { day: 16, title: 'Drive to Kathmandu & Departure',                                    description: '4–5 hours drive then airport transfer.' },
    ],
    included: [
      'All essential permits including Langtang National Park entry permit and TIMS card',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'the Heritage Trail',
  },

  'langtang-gosaikunda-trek': {
    title: 'Langtang Gosaikunda Trek',
    duration: '15 Days',
    difficulty: 'Challenging',
    elevation: '4,380 m / 14,370 ft (Gosaikunda Lake)',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/gosaikunda-region.jpg', '/assets/images/gosaikunda-lake.jpg', '/assets/images/langtang-valley.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Langtang Gosaikunda Trek', href: '#' },
    ],
    description: `A sacred high-altitude journey combining the pristine Langtang Valley with the mythical Gosaikunda Lake — one of Hinduism's most revered pilgrimage sites at 4,380m. A trek of mountains, spirituality, and Himalayan wilderness.`,
    highlights: [
      'Gosaikunda Lake (4,380m) — one of Nepal\'s most sacred Hindu and Buddhist pilgrimage sites',
      'Langtang Valley and Kyanjin Gompa (3,830m)',
      'Views of Langtang Lirung (7,227m) and the Ganesh Himal',
      'Laurebinayak Pass crossing with panoramic mountain views',
      'Dense rhododendron and bamboo forests',
      'Traditional Tamang and Sherpa village culture',
      'Langtang National Park wildlife and biodiversity',
    ],
    overview: [
      `The Langtang Gosaikunda Trek combines the natural beauty of the Langtang Valley with the spiritual significance of the sacred Gosaikunda Lake. Starting from Syabrubesi, the trail winds through traditional Tamang villages and dense forests to Kyanjin Gompa, then continues south to the sacred alpine lakes of Gosaikunda at 4,380m.`,
      `Gosaikunda is one of the most important pilgrimage sites in Nepal for both Hindus and Buddhists, and the sight of the sacred lake surrounded by high peaks is both spiritually moving and visually stunning. The crossing of Laurebinayak Pass adds a demanding but rewarding high-altitude dimension to the trek.`,
      `The trek offers a beautiful combination of natural and cultural experiences — from the wildlife-rich forests of Langtang National Park to the ancient monasteries and prayer sites along the route. It's a journey that engages all the senses and leaves a lasting impression.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner.' },
      { day: 3,  title: 'Drive to Syabru Besi (1,503 m)',                                    description: '7–9 hours by bus.' },
      { day: 4,  title: 'Trek to Lama Hotel (2,500 m)',                                      description: '5–6 hours through dense forest.' },
      { day: 5,  title: 'Trek to Langtang Village (3,430 m)',                                description: '5–6 hours through alpine meadows.' },
      { day: 6,  title: 'Trek to Kyanjin Gompa (3,830 m)',                                   description: '4–5 hours to the spiritual heart of Langtang.' },
      { day: 7,  title: 'Exploration Day at Kyanjin Gompa',                                 description: 'Optional Tserko Ri hike and cheese factory visit.' },
      { day: 8,  title: 'Trek Back to Lama Hotel (2,500 m)',                                 description: '5–6 hours descending.' },
      { day: 9,  title: 'Trek to Thulo Syabru (2,150 m)',                                    description: '5–6 hours.' },
      { day: 10, title: 'Trek to Sing Gompa (3,330 m)',                                      description: '5–6 hours.' },
      { day: 11, title: 'Trek to Gosaikunda Lake (4,380 m)',                                 description: '5–6 hours to the sacred lake.' },
      { day: 12, title: 'Cross Laurebinayak Pass (4,610 m) & Trek to Ghopte (3,530 m)',     description: '6–7 hours. Challenging high pass crossing.' },
      { day: 13, title: 'Trek to Melamchi Gaon (2,530 m)',                                   description: '6–7 hours descending into Helambu.' },
      { day: 14, title: 'Trek to Melamchi Pul Bazaar (870 m)',                               description: '5–6 hours. Final trekking day.' },
      { day: 15, title: 'Drive to Kathmandu & Departure',                                    description: '4–5 hours drive then airport transfer.' },
    ],
    included: [
      'All essential permits including Langtang National Park entry permit and TIMS card',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Gosaikunda',
  },

  'langtang-gosaikunda-helambu-trek': {
    title: 'Langtang Gosaikunda Helambu Trek',
    duration: '18 Days',
    difficulty: 'Challenging',
    elevation: '4,610 m / 15,120 ft (Laurebinayak Pass)',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Hiking',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/helambu.jpg', '/assets/images/gosainkunda.jpg', '/assets/images/langtang-valley.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Treks', href: '/Nepal#trekking' },
      { label: 'Langtang Gosaikunda Helambu Trek', href: '#' },
    ],
    description: `The grand traverse of the Langtang region — from the heart of Langtang Valley to the sacred Gosaikunda Lake, over the high Laurebinayak Pass, and down through the verdant Helambu Valley in a complete 18-day Himalayan journey of mountains, culture, and spiritual discovery.`,
    highlights: [
      'Complete traverse of all three Langtang sub-regions: Langtang, Gosaikunda, and Helambu',
      'Kyanjin Gompa and Langtang Valley wilderness',
      'Sacred Gosaikunda Lake (4,380m) — one of Nepal\'s most revered pilgrimage sites',
      'Laurebinayak Pass (4,610m) — demanding high-altitude crossing with panoramic views',
      'Helambu Valley — peaceful forested landscapes and diverse Sherpa culture',
      'Himalayan panoramas along the entire route',
      'Combination of adventure, spirituality, and cultural immersion',
    ],
    overview: [
      `The Langtang Gosaikunda Helambu Trek is the most comprehensive journey through the Langtang region, combining all three distinct sub-regions in a single 18-day adventure. Starting from Syabrubesi, the trek moves through the pristine Langtang Valley to Kyanjin Gompa, then follows the sacred trail to Gosaikunda Lake, crosses the Laurebinayak Pass, and descends through the lush forests and traditional villages of the Helambu Valley.`,
      `This is a trek of great variety — from the dramatic alpine scenery of Langtang to the spiritual atmosphere of the sacred lakes to the warm cultural richness of Helambu. The Laurebinayak Pass crossing at 4,610m is the physical and emotional high point, offering sweeping panoramas before the long and rewarding descent to the Kathmandu Valley.`,
      `Whether you are an experienced trekker or a dedicated first-timer with strong fitness, this trek offers an unforgettable experience in Nepal's diverse Himalayan landscapes. The proximity to Kathmandu means minimal travel time, making it accessible for those with tighter schedules.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner.' },
      { day: 3,  title: 'Drive to Syabru Besi (1,503 m)',                                    description: '7–9 hours. Overnight at guesthouse.' },
      { day: 4,  title: 'Trek to Lama Hotel (2,500 m)',                                      description: '5–6 hours through forest.' },
      { day: 5,  title: 'Trek to Langtang Village (3,430 m)',                                description: '5–6 hours.' },
      { day: 6,  title: 'Trek to Kyanjin Gompa (3,830 m)',                                   description: '4–5 hours.' },
      { day: 7,  title: 'Exploration Day at Kyanjin Gompa',                                 description: 'Optional Tserko Ri hike and monastery visit.' },
      { day: 8,  title: 'Trek Back to Lama Hotel (2,500 m)',                                 description: '5–6 hours.' },
      { day: 9,  title: 'Trek to Thulo Syabru (2,150 m)',                                    description: '5–6 hours.' },
      { day: 10, title: 'Trek to Sing Gompa (3,330 m)',                                      description: '5–6 hours.' },
      { day: 11, title: 'Trek to Gosaikunda Lake (4,380 m)',                                 description: '5–6 hours to the sacred lake.' },
      { day: 12, title: 'Cross Laurebinayak Pass (4,610 m) & Trek to Ghopte (3,530 m)',     description: '6–7 hours. The trek\'s high point.' },
      { day: 13, title: 'Trek to Melamchi Gaon via Tharepati Pass (2,530 m)',               description: '6–7 hours descending into Helambu.' },
      { day: 14, title: 'Trek to Tarkeghyang (2,600 m)',                                     description: '5–6 hours through Helambu valley.' },
      { day: 15, title: 'Trek to Shermathang (2,590 m)',                                     description: '5–6 hours.' },
      { day: 16, title: 'Trek to Melamchi Pul Bazaar (870 m)',                               description: '5–6 hours. Final trekking day.' },
      { day: 17, title: 'Drive from Melamchi Pul Bazaar to Kathmandu',                      description: '4–5 hours by private tourist vehicle.' },
      { day: 18, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],
    included: [
      'All essential permits including Langtang National Park entry permit and TIMS card',
      'Airport transportation to/from Kathmandu hotels and airport',
      'Three-star twin-sharing hotel accommodation in Kathmandu',
      'Welcome dinner at a traditional Nepali restaurant',
      'Half-day guided Kathmandu sightseeing tour including entrance fees and one UNESCO heritage site',
      'All government and local taxes',
      'All ground transportation listed in itinerary',
      'Teahouse accommodation during trek',
      'Professional trekking guide/group leader and porter (related expenses included)',
      'Meals during trek: breakfast, lunch, and dinner',
      'Health & Safety Equipment: oxygen cans, medical kit, oximeter, blood pressure monitor, satellite phone',
      'Sleeping bag and down jacket during trek',
      'Nepal Himal Adventures souvenirs: Duffel bag, T-shirt, Sun hat, Trekking Map, Buff, Sleeping Bag, Trip completion certificate',
    ],
    excluded: [
      'Nepali visa fees',
      'Personal expenses including food while not on trek',
      'International flight fares',
      'Emergency medical rescue / evacuation expenses',
      'Staff tipping',
      'Extra night accommodation in Kathmandu on early arrival or late departure',
      'Travel or medical insurance',
      'Optional tours, sightseeing, and activities during free time',
      'Donations to locals or organizations',
      'Snacks during trek',
      'Other personal expenses such as laundry, charging, showers, etc.',
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'the Grand Traverse',
  },

};