import { TrekData } from './ExpeditionPage';

export const expeditions: Record<string, TrekData> = {
  'everest-base-camp-lobuche-east': {
    title: 'Everest Base Camp & Lobuche East',
    duration: '19 Days',
    difficulty: 'Challenging / Semi-Technical',
    elevation: '6,119 m / 20,070 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Strenuous Trekking / Moderate Technical Climbing',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/everest-base-camp.jpg', '/assets/images/lobuche-east.jpg', '/assets/images/khumbu.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Everest Base Camp & Lobuche East', href: '#' },
    ],
    description: `The Khumbu Double Crown: A premier progression from the world's most historic base camp to a 6,000-meter alpine summit. This 19-day expedition combines the legendary Everest Base Camp trek with a technical ascent of Lobuche East (6,119m).`,
    highlights: [
      'Summit Lobuche East at 6,119m — a world-class mountaineering achievement',
      'The Grand Stand of the Giants — panoramic views of Everest, Lhotse, Nuptse, Makalu, Cho Oyu, and Ama Dablam',
      'Visit the world\'s greatest base camp at 5,364m',
      'The masterpiece vantage point of Kala Patthar (5,550m)',
      'Pre-climb glacier training academy',
      'Spiritual sanctuary of Tengboche Monastery (3,867m)',
      'Explore the vibrant Sherpa hub of Namche Bazaar (3,440m)',
    ],
    overview: [
      `The Everest Base Camp and Lobuche East expedition is a prestigious high-altitude challenge that combines the world's most famous trek with a technical 6,000m summit. The journey begins with a flight to Lukla (2,846m) and follows the legendary Khumbu trail toward Everest Base Camp (5,364m) and Kala Patthar (5,545m) before shifting focus to the ultimate objective: the 6,119m summit of Lobuche East.`,
      `Success on this dual-objective mission depends on elite-level physical conditioning, focusing on cardiovascular endurance and lower-body strength at least 4 months before arrival. The terrain transitions from rocky glacial moraines to steep, technical ice and snow sections requiring professional mountaineering boots, crampons, and harness systems. Required permits include the Sagarmatha National Park permit, the Khumbu local permit, and the NMA climbing permit for Lobuche.`,
      `The expedition reaches its dramatic climax at the summit of Lobuche East (6,119m), providing one of the most spectacular vantage points in the world, with a direct line of sight to Everest, Lhotse, Nuptse, and Ama Dablam. This experience bridges the gap between trekking and true mountaineering, connecting the historical legacy of the Everest trail with the physical triumph of a Himalayan peak.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Trek Preparation',                         description: 'Guided tour of historic landmarks, gear check, and welcome dinner.' },
      { day: 3,  title: 'Fly to Lukla & Trek to Phakding (2,610 m)',                        description: '35-minute flight. Trek 3–4 hours downhill to Phakding.' },
      { day: 4,  title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '5–6 hours through pine forests and suspension bridges.' },
      { day: 5,  title: 'Acclimatization Day at Namche Bazaar',                             description: 'Hike to Hotel Everest View (3,962m) for stunning panoramas.' },
      { day: 6,  title: 'Trek to Tengboche Monastery (3,860 m)',                            description: '5–6 hours to the famous ridge-top monastery.' },
      { day: 7,  title: 'Trek to Dingboche (4,410 m)',                                       description: '5–6 hours through alpine villages to Dingboche.' },
      { day: 8,  title: 'Chukhung Valley Day Hike (4,730m) - Acclimatization',              description: '4–5 hours round trip. Views of Island Peak and Lhotse face.' },
      { day: 9,  title: 'Trek to Lobuche (4,930 m)',                                        description: '5–6 hours. Pass the memorial plateau at Chukpo Lari.' },
      { day: 10, title: 'Trek to Everest Base Camp (5,364m) & Return to Gorak Shep',       description: '7–8 hours total. Stand at the foot of the Khumbu Icefall.' },
      { day: 11, title: 'Hike Kala Patthar (5,555m) & Trek to Lobuche',                     description: '5–6 hours. Pre-dawn climb for sunrise over Everest.' },
      { day: 12, title: 'Trek to Lobuche East Base Camp (4,950 m)',                         description: '5–6 hours to tented wilderness camp. Gear inspection.' },
      { day: 13, title: 'Move to Lobuche High Camp (5,400 m)',                              description: 'Short but demanding carry. Crampon and rope technique review.' },
      { day: 14, title: 'Summit Day: Lobuche East (6,119m) & Return to Base Camp',         description: '10–11 hours. 2:00-3:00 AM alpine start. Fixed ropes on headwall.' },
      { day: 15, title: 'Climbing Weather Contingency / Buffer Day',                       description: 'Reserve day for secondary summit window or rest.' },
      { day: 16, title: 'Trek to Pangboche (3,930 m)',                                      description: '6–7 hours. Rewarding descent from high altitudes.' },
      { day: 17, title: 'Trek to Namche Bazaar (3,440 m)',                                  description: '6–7 hours. Celebratory meal in the Sherpa capital.' },
      { day: 18, title: 'Trek to Lukla (2,840 m)',                                          description: '5–6 hours. Final day on the trail.' },
      { day: 19, title: 'Fly Back to Kathmandu',                                            description: 'Morning flight back to Kathmandu. Farewell dinner.' },
      { day: 20, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'EBC & Lobuche East',
  },

  'pisang-peak': {
    title: 'Pisang Peak Climbing',
    duration: '15 Days',
    difficulty: 'Challenging / Non-Technical',
    elevation: '6,091 m / 19,980 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Moderate Climbing',
    accommodation: 'Tea House / Hotel & Base Camp (Mini Tented Village)',
    heroImages: ['/assets/images/pisang-peak.jpg', '/assets/images/annapurna-circuit.jpg', '/assets/images/manang.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Pisang Peak Climbing', href: '#' },
    ],
    description: `One of the most accessible 6,000m summits in the Annapurna region, Pisang Peak offers the perfect "sightseeing peak" for aspiring mountaineers. This 15-day expedition follows the scenic Annapurna Circuit trail to the 6,091m summit.`,
    highlights: [
      'Summit Pisang Peak (6,091m) — the Pyramid Summit of the Annapurna region',
      'The "Double High" Experience — unparalleled mountain views',
      'The Gates to Heaven (Swarga Dwari)',
      'A bird\'s-eye view of the entire Annapurna Massif',
      'Upper Pisang cultural immersion in traditional Tibetan-Buddhist villages',
      'Sacred Muktinath Temple — a pilgrimage site for Hindus and Buddhists',
      'The high-altitude desert of Mustang',
    ],
    overview: [
      `The Pisang Peak Climbing expedition is widely considered one of the most accessible 6,000m summits in the Annapurna region, making it an ideal "sightseeing peak" for aspiring mountaineers. The journey typically begins with a drive to Chame (2,670m) and follows the scenic Annapurna Circuit trail toward the 6,091m summit.`,
      `Success on this climb depends on solid cardiovascular fitness and lower-body endurance, with training recommended to start at least 3 months before departure. While the route is categorized as non-technical, the final ascent involves a steep snow headwall of approximately 45-50 degrees, requiring crampons, an ice axe, and fixed ropes. Required permits include the NMA climbing permit, ACAP permit, and TIMS card.`,
      `The trek reaches its rewarding climax at the summit of Pisang Peak (6,091m), where climbers are treated to a spectacular 360-degree panorama of the Damodar Himalaya and the Annapurna range. The final leg follows a reflective journey over Thorong La Pass (5,416m) and down to the sacred temples of Muktinath.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,350 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Preparation',                        description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Drive Kathmandu to Dharapani (1,860 m)',                           description: '8–10 hours drive. Private 4WD alongside Trishuli River.' },
      { day: 4,  title: 'Trek Dharapani to Chame (2,670 m)',                                description: '5–6 hours through pine, fir, and rhododendron forests.' },
      { day: 5,  title: 'Trek Chame to Upper Pisang (3,300 m)',                              description: '5–6 hours. Views of Paungda Danda rock face.' },
      { day: 6,  title: 'Acclimatization Day in Upper Pisang',                              description: 'Explore monastery and enjoy views of Annapurna II and III.' },
      { day: 7,  title: 'Trek to Pisang Peak Base Camp (4,380 m)',                          description: '6–7 hours. Steep uphill through alpine pastures.' },
      { day: 8,  title: 'Move to High Camp (5,400 m)',                                      description: '6–7 hours. Demanding carry up steep ridge line.' },
      { day: 9,  title: 'Summit Day: Pisang Peak (6,091m) & Descend to Base Camp',          description: '9–10 hours. 2:00 AM alpine start. Fixed lines on headwall.' },
      { day: 10, title: 'Trek from Base Camp to Manang (3,540 m)',                          description: '6–7 hours. Descent through dry, rain-shadow landscape.' },
      { day: 11, title: 'Trek Manang to Yak Kharka (4,110 m)',                              description: '5–6 hours. Climb through juniper bushes and grazing pastures.' },
      { day: 12, title: 'Trek to Thorong Phedi (4,450 m)',                                  description: '5–6 hours. Base settlement at foot of the high pass.' },
      { day: 13, title: 'Cross Thorong La Pass (5,416m) to Muktinath (3,760m)',             description: '7–8 hours. 4:00 AM start. Prayer flags at summit.' },
      { day: 14, title: 'Drive/Fly to Pokhara & Return to Kathmandu',                       description: 'Morning drive to Jomsom, flight to Pokhara, then to Kathmandu.' },
      { day: 15, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Pisang Peak',
  },

  'yala-peak': {
    title: 'Yala Peak Climbing',
    duration: '14 Days',
    difficulty: 'Challenging',
    elevation: '5,500 m / 18,045 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Climbing',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/yala-peak.jpg', '/assets/images/langtang.jpg', '/assets/images/kyanjin-gompa.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Yala Peak Climbing', href: '#' },
    ],
    description: `The perfect entry-level peak climbing experience in the Langtang region. Yala Peak (5,500m) offers a scenic, direct introduction to Himalayan glacier mountaineering with stunning views of Shishapangma, the only 8,000m peak completely in Tibet.`,
    highlights: [
      'Summit Yala Peak (5,500m) — a gateway to Himalayan mountaineering',
      'The staggering Shishapangma horizon — views of the Tibetan 8,000m peak',
      'Deep Tamang cultural heritage integration',
      'The sacred sanctuary of Kyanjin Gompa (3,830m)',
      'The rushing Langtang Khola gorge',
      'Spectacular views of Langtang Lirung (7,227m) and Dorje Lakpa',
      'Optional hike to Tserko Ri (4,984m) for sweeping panoramas',
    ],
    overview: [
      `The Yala Peak Climbing expedition is an ideal entry-level mountaineering experience that requires good physical fitness and a spirit for adventure. The journey begins with a scenic drive from Kathmandu to Syabrubesi (1,500m) and winds through beautiful Langtang National Park toward the summit of Yala Peak at 5,520m.`,
      `Success at this peak depends on consistent cardiovascular training and hiking experience at least 2 months before departure. The terrain transitions from lush rhododendron forests to rocky moraines and snow-covered slopes, requiring sturdy trekking boots, crampons, and a versatile layering system. Required permits include the Langtang National Park entry permit and TIMS card.`,
      `The trek reaches its rewarding climax at the summit of Yala Peak (5,520m), where climbers are treated to a spectacular panorama of Shishapangma and the sprawling Ganesh Himal range. This is a perfect introduction to Himalayan mountaineering, connecting the vibrant culture of the Langtang Valley to pristine, high-altitude wilderness.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Preparation',                        description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Drive to Syabru Besi (1,462 m)',                                   description: '7–8 hours drive through Langtang National Park.' },
      { day: 4,  title: 'Trek to Lama Hotel (2,500 m)',                                     description: '5–6 hours through dense forests of oak and bamboo.' },
      { day: 5,  title: 'Trek to Langtang Village (3,400 m)',                               description: '5–6 hours. First glimpses of Langtang Lirung.' },
      { day: 6,  title: 'Trek to Kyanjin Gompa (3,830 m)',                                  description: '4–5 hours. Surrounded by an amphitheater of snowy peaks.' },
      { day: 7,  title: 'Kyanjin Gompa Exploration & Acclimatization',                      description: 'Hike Kyanjin Ri (4,773m) or Tserko Ri (4,984m).' },
      { day: 8,  title: 'Trek to Yala Peak Base Camp (4,500 m)',                            description: '5–6 hours. Steep climb along rugged ridge line.' },
      { day: 9,  title: 'Summit Day: Yala Peak (5,500m) & Return to Kyanjin Gompa',        description: '8–9 hours. 2:00 AM alpine start. Non-technical but demanding.' },
      { day: 10, title: 'Climbing Weather Contingency Day',                                 description: 'Reserve day for secondary summit window or rest.' },
      { day: 11, title: 'Trek back to Lama Hotel (2,500 m)',                                description: '5–6 hours. Long, rewarding descent down valley.' },
      { day: 12, title: 'Trek to Syabru Besi (1,462 m)',                                    description: '6–7 hours. Final day on the trail.' },
      { day: 13, title: 'Drive back to Kathmandu (1,400 m)',                                description: '7–8 hours drive. Farewell dinner.' },
      { day: 14, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Yala Peak',
  },

  'everest-high-passes-island-peak': {
    title: 'Everest High Passes & Island Peak',
    duration: '24 Days',
    difficulty: 'Challenging / Semi-Technical',
    elevation: '6,187 m / 20,299 ft',
    season: 'Feb–Jun & Sep–Dec',
    groupSize: '2 or more',
    activity: 'Multi-Activity (Trekking & Climbing)',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/everest-high-passes.jpg', '/assets/images/island-peak-summit.jpg', '/assets/images/gokyo-lakes.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Everest High Passes & Island Peak', href: '#' },
    ],
    description: `The ultimate Khumbu Grand Slam: three 5,000-meter passes and a 6,000-meter summit achievement. This 24-day expedition combines the legendary Three High Passes—Renjo La, Cho La, and Kongma La—with a technical ascent of Island Peak (6,189m).`,
    highlights: [
      'Complete the Three High Passes trilogy: Renjo La (5,360m), Cho La (5,420m), and Kongma La (5,535m)',
      'Summit Island Peak (Imja Tse) at 6,189m',
      'Photography across the region with guaranteed ascents of Gokyo Ri (5,357m) and Kala Patthar (5,550m)',
      'Visit Everest Base Camp (5,364m)',
      'The shimmering turquoise Gokyo Lakes',
      'Traverse active moving glaciers including the Ngozumpa Glacier',
      'Front-row view of Lhotse\'s massive south face from the summit ridge',
    ],
    overview: [
      `The Everest High Passes and Island Peak Expedition is the definitive alpine challenge in the Khumbu region, masterfully combining a massive high-altitude circuit with a technical mountaineering summit. The journey targets the completion of the legendary Three High Passes—Renjo La (5,360m), Cho La (5,420m), and Kongma La (5,535m)—alongside Everest Base Camp (5,364m).`,
      `Success on this demanding itinerary requires exceptional physical preparation and mental toughness, with training focused on weighted uphill endurance initiated at least 4 to 6 months before departure. Terrain includes shifting glacial moraines, steep ice-glazed passes, and vertical headwalls requiring crampons, ice axe, and fixed-rope jumar ascents. Required permits include Sagarmatha National Park permit, Khumbu local permit, and NMA peak climbing permit.`,
      `The expedition reaches its grand climax on the knife-edge summit ridge of Island Peak (6,189m), offering a surreal, front-row view of Lhotse's massive south face. The transition from teahouse trekking to full tented camping at Island Peak Base Camp marks the final shift into true mountaineering.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Trek Preparation',                         description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Fly to Lukla & Trek to Phakding (2,610 m)',                        description: '3–4 hours gentle trek to Phakding.' },
      { day: 4,  title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '5–6 hours. Steep climb to the Sherpa capital.' },
      { day: 5,  title: 'Namche Bazaar Rest Day (Acclimatization)',                         description: 'Hike to Hotel Everest View (3,880m).' },
      { day: 6,  title: 'Trek to Phortse Tenga (3,680 m)',                                   description: '5–6 hours. Leave main trail to quiet valley.' },
      { day: 7,  title: 'Trek to Machhermo (4,470 m)',                                       description: '5–6 hours. Views of Cho Oyu.' },
      { day: 8,  title: 'Trek to Gokyo Lakes (4,800 m)',                                     description: '5–6 hours. Walk alongside pristine glacial lakes.' },
      { day: 9,  title: 'Hike Gokyo Ri (5,483m) & Return to Gokyo',                         description: '5–6 hours. Panoramic views of four 8,000m peaks.' },
      { day: 10, title: 'Trek to Thangnak (4,500 m)',                                        description: '4–5 hours. Traverse Ngozumpa Glacier moraine.' },
      { day: 11, title: 'Cross Cho La Pass (5,368m) & Trek to Dzongla (4,830m)',            description: '7–8 hours. Pre-dawn start over icy glacier plateau.' },
      { day: 12, title: 'Trek to Lobuche (4,910 m)',                                        description: '4–5 hours. Panoramic trail above Cholaste Lake.' },
      { day: 13, title: 'Hike Kala Patthar (5,555m) & Return to Gorak Shep',                description: '7–8 hours. Sunset views over Mount Everest.' },
      { day: 14, title: 'Visit Everest Base Camp (5,364m) & Return to Lobuche',             description: '8–9 hours. Explore historic site at Khumbu Icefall.' },
      { day: 15, title: 'Cross Kongma La Pass (5,535m) & Trek to Chukhung',                 description: '8–9 hours. The highest of the three passes.' },
      { day: 16, title: 'Trek to Island Peak Base Camp (5,240 m)',                          description: '4–5 hours. Along Imja Glacier lateral moraine.' },
      { day: 17, title: 'Base Camp Rest & Skills Training',                                 description: 'Practice fixed-rope techniques and gear check.' },
      { day: 18, title: 'Summit Island Peak (6,187m) & Return to Chukhung',                 description: '9–10 hours. Midnight start. Fixed-line headwall.' },
      { day: 19, title: 'Climbing Weather Contingency Day',                                 description: 'Reserve day for secondary summit window.' },
      { day: 20, title: 'Trek to Tengboche (3,860 m)',                                      description: '6–7 hours. Descend through Imja Valley.' },
      { day: 21, title: 'Trek to Namche Bazaar via Khumjung',                               description: '5–6 hours. Visit Khumjung monastery.' },
      { day: 22, title: 'Trek to Lukla (2,840 m)',                                          description: '6–7 hours. Final day on the trail.' },
      { day: 23, title: 'Fly Back to Kathmandu',                                            description: 'Morning flight back to Kathmandu.' },
      { day: 24, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'High Passes & Island Peak',
  },

  'ama-dablam': {
    title: 'Ama Dablam Expedition',
    duration: '29 Days',
    difficulty: 'Technical / Advanced',
    elevation: '6,812 m / 22,349 ft',
    season: 'Spring (Apr–May) & Autumn (Oct–Nov)',
    groupSize: '2 or more',
    activity: 'Technical Mountaineering (Rock, Ice & Mixed)',
    accommodation: 'Tea House / Hotel & High Camps (Tented)',
    heroImages: ['/assets/images/ama-dablam.jpg', '/assets/images/ama-dablam-summit.jpg', '/assets/images/khumbu.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Ama Dablam Expedition', href: '#' },
    ],
    description: `The world's most aesthetic summit (6,812m) and a definitive "rite of passage" for experienced alpinists. Ama Dablam's iconic pyramid shape requires mastery of technical rock, ice, and mixed-terrain climbing on the legendary Southwest Ridge.`,
    highlights: [
      'Summit Ama Dablam (6,812m) — one of the world\'s most beautiful mountains',
      'The iconic "Mother\'s Necklace" — witness the massive hanging glacier that gives the mountain its name',
      'The legendary Yellow Tower — a technical rock climbing challenge',
      'Spectacular "bird\'s-eye" high camps with unrivaled 360-degree views',
      'Unrivaled 360-degree views of Everest, Lhotse, and Makalu',
      'Cultural trek through the Khumbu to Base Camp',
      'A "Grail" for seasoned climbers seeking the ultimate Himalayan test',
    ],
    overview: [
      `The Ama Dablam Expedition is a world-renowned mountaineering challenge that stands as a definitive "rite of passage" for experienced alpinists. Rising to 6,812m, the mountain's iconic pyramid shape requires mastery of technical rock, ice, and mixed-terrain climbing. The journey begins with a flight to Lukla and follows the classic Khumbu trail before diverting to Ama Dablam Base Camp.`,
      `Success on Ama Dablam depends on advanced technical proficiency, including comfort on fixed ropes, vertical rock sections (up to 5.7 grade), and steep ice pitches. Climbers should initiate an elite-level training program at least 6 months prior, focusing on upper-body strength, precision footwork, and sustained cardiovascular power. A specific climbing permit from the Department of Tourism, plus Sagarmatha National Park and Khumbu permits, is required.`,
      `The expedition reaches its breathtaking climax at the sharp summit of Ama Dablam (6,812m), providing an unparalleled, close-up panorama of Everest, Lhotse, and Makalu. Standing on the summit demonstrates technical composure and climbing precision in one of the world's most spectacular alpine arenas.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Briefing',                           description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Final Preparation & Permit Day in Kathmandu',                      description: 'Permit processing and last-minute equipment rentals.' },
      { day: 4,  title: 'Fly to Lukla & Trek to Phakding (2,610 m)',                        description: '3–4 hours trek. Meet your climbing crew.' },
      { day: 5,  title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '5–6 hours. Cross the famous Hillary Suspension Bridge.' },
      { day: 6,  title: 'Namche Rest Day (Acclimatization)',                                description: 'Hike to Hotel Everest View (3,880m). Views of Ama Dablam.' },
      { day: 7,  title: 'Trek to Tengboche Monastery (3,860 m)',                            description: '5–6 hours. Iconic ridge-top monastery.' },
      { day: 8,  title: 'Trek to Pangboche (3,930 m)',                                      description: '2–3 hours. Home to the oldest monastery in Khumbu.' },
      { day: 9,  title: 'Trek to Ama Dablam Base Camp (4,600 m)',                           description: '5–6 hours. Private kitchen and tented camp established.' },
      { day: 10, title: 'Base Camp Rest & Acclimatization',                                 description: 'Gear sorting, fitting, and traditional Puja ceremony.' },
      { day: 11, title: 'Ama Dablam Climbing Period — Rotation 1 to Camp 1 (5,700m)',       description: 'Technical rock and ice climbing on Southwest Ridge.' },
      { day: 12, title: 'Climbing Period — Return to Base Camp',                           description: 'Descend to Base Camp for rest and recovery.' },
      { day: 13, title: 'Climbing Period — Rest Day at Base Camp',                         description: 'Hydration, gear prep, and route strategy.' },
      { day: 14, title: 'Climbing Period — Rotation to Camp 2 (5,900m)',                    description: 'Move higher on the mountain. Establish Camp 2.' },
      { day: 15, title: 'Climbing Period — Return to Base Camp',                           description: 'Descend for final rest before summit push.' },
      { day: 16, title: 'Climbing Period — Rest Day at Base Camp',                         description: 'Final preparations and weather assessment.' },
      { day: 17, title: 'Climbing Period — Move to Camp 1',                                 description: 'Begin summit rotation. Sleep at Camp 1.' },
      { day: 18, title: 'Climbing Period — Move to Camp 2',                                 description: 'Ascend to high camp for summit positioning.' },
      { day: 19, title: 'Summit Push — Ama Dablam (6,812m) & Descend to Camp 2',           description: 'Summit via Yellow Tower and exposed ridges.' },
      { day: 20, title: 'Climbing Period — Descend to Base Camp',                          description: 'Return to Base Camp after successful summit.' },
      { day: 21, title: 'Weather Contingency / Reserve Day',                                description: 'Built-in buffer for summit window.' },
      { day: 22, title: 'Weather Contingency / Reserve Day',                                description: 'Additional buffer for mountain conditions.' },
      { day: 23, title: 'Weather Contingency / Reserve Day',                                description: 'Final reserve day for summit attempt.' },
      { day: 24, title: 'Trek to Namche Bazaar (3,440 m)',                                  description: '6–7 hours. Say goodbye to the mountain.' },
      { day: 25, title: 'Trek to Lukla (2,840 m)',                                          description: '6–7 hours. Celebrate with your crew.' },
      { day: 26, title: 'Fly to Kathmandu',                                                 description: 'Morning flight back to Kathmandu.' },
      { day: 27, title: 'Reserve Day in Kathmandu',                                         description: 'Rest, shopping, and relaxation.' },
      { day: 28, title: 'Departure',                                                        description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Ama Dablam',
  },

  'mera-peak': {
    title: 'Mera Peak Climbing',
    duration: '20 Days',
    difficulty: 'Challenging / Semi-Technical',
    elevation: '6,470 m / 21,227 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Climbing',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/mera-peak.jpg', '/assets/images/hinku-valley.jpg', '/assets/images/mera-summit.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Mera Peak Climbing', href: '#' },
    ],
    description: `The roof of trekking peaks: the ultimate high-altitude walking expedition across hidden valleys and wild glacial plateaus. Mera Peak (6,470m) stands as the highest official "trekking peak" in Nepal, offering unparalleled panoramic views of five 8,000-meter peaks.`,
    highlights: [
      'Summit the highest trekking peak in Nepal at 6,470m',
      'The five-8,000er summit masterpiece — views of Everest, Lhotse, Cho Oyu, Makalu, and Kanchenjunga',
      'The wild, unspoiled Hinku Valley entry —远离 crowded EBC trail',
      'Pristine high camp staging at 5,780m',
      'Gradual, foot-safe glacier march suitable for novice climbers',
      'Deeply immersive wilderness approach through Panggom, Ramailo Danda, and Chhatra Khola',
      'Visit century-old Buddhist stupas like Lungsumbga Gompa',
    ],
    overview: [
      `Mera Peak (6,476m) stands crowned as the highest official "trekking peak" in Nepal, offering an unparalleled introductory mountaineering expedition into the spectacular Mahalangur section of the Himalayas. Situated on the edge of the pristine Hinku Valley, this expedition is highly sought after by ambitious trekkers and novice climbers looking to transition into high-altitude alpine mountaineering.`,
      `While classified as a non-technical "walk-up" peak, achieving success on Mera Peak demands excellent physical fitness. The approach requires navigating extensive, heavily crevassed high-altitude glaciers using crampons, an ice axe, and fixed-rope team travel. Required permits include the NMA Mera Peak Climbing Permit, Makalu Barun National Park Entry Permit, and Khumbu Pasang Lhamu Rural Municipality Permit.`,
      `The expedition reaches its breathtaking climax on the small, snow-dome summit of Mera Peak, rewarding climbers with what is widely considered the finest panoramic viewpoint in the entire Himalaya — an unobstructed view of five of the world's fourteen 8,000-meter peaks simultaneously.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Preparation',                        description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Fly to Lukla & Trek to Paiya/Chutok (2,800 m)',                    description: '3–4 hours. Leave main trail to remote farmlands.' },
      { day: 4,  title: 'Trek to Pangkongma (2,900 m)',                                     description: '6–7 hours. Cross Khari La pass.' },
      { day: 5,  title: 'Trek to Nashing Dingma (2,963 m)',                                 description: '6–7 hours. Cross Pangkongma La pass.' },
      { day: 6,  title: 'Trek to Chholem Kharka (3,600 m)',                                 description: '6–7 hours. Summer yak grazing pastures.' },
      { day: 7,  title: 'Trek to Khola Kharka (4,270 m)',                                   description: '6–7 hours. Cross Panch Pokhari pass.' },
      { day: 8,  title: 'Trek to Kothe (3,600 m)',                                          description: '6–7 hours. Rejoin main Hinku Valley trail.' },
      { day: 9,  title: 'Trek to Tangnag (4,350 m)',                                        description: '6–7 hours. Visit 200-year-old Lungsumbga Gompa.' },
      { day: 10, title: 'Tangnag Rest Day (Acclimatization)',                               description: 'Hike toward Sabai Tsho glacial lake.' },
      { day: 11, title: 'Trek to Khare (4,900 m)',                                          description: '4–5 hours. Main alpine base for Mera teams.' },
      { day: 12, title: 'Khare Rest & Technical Climbing Practice',                        description: 'Fit double boots, practice jumar ascents.' },
      { day: 13, title: 'Trek to Mera High Camp (5,800 m)',                                 description: '7–8 hours. Snow climb across Mera Glacier.' },
      { day: 14, title: 'Summit Day: Mera Peak (6,470m) & Return to Khare',                description: '10–15 hours. 1:00-2:00 AM alpine start.' },
      { day: 15, title: 'Climbing Weather Contingency Day',                                 description: 'Reserve day for secondary summit window.' },
      { day: 16, title: 'Trek to Kothe (3,600 m)',                                          description: '6–7 hours. Rewarding descent.' },
      { day: 17, title: 'Trek to Thuli Kharka (4,200 m)',                                   description: '6–7 hours. High-perched settlement.' },
      { day: 18, title: 'Trek to Lukla via Zatrwa La Pass (4,610m)',                        description: '7–8 hours. Final pass crossing.' },
      { day: 19, title: 'Fly Back to Kathmandu',                                            description: 'Morning flight back to Kathmandu.' },
      { day: 20, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Mera Peak',
  },

  'pisang-peak-thorong-la': {
    title: 'Pisang Peak & Thorung La Pass',
    duration: '22 Days',
    difficulty: 'Strenuous / Semi-Technical',
    elevation: '6,091 m / 19,980 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Strenuous Trekking / Technical (Snow & Ice)',
    accommodation: 'Tea House / Hotel & Base Camp (Mini Tented Village)',
    heroImages: ['/assets/images/pisang-peak.jpg', '/assets/images/thorong-la.jpg', '/assets/images/annapurna-circuit.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Pisang Peak & Thorung La Pass', href: '#' },
    ],
    description: `Follow the Marsyangdi River to the stars, standing atop Pisang Peak for a bird's-eye view before crossing the world's most famous pass. This 22-day expedition combines a technical 6,000m summit with the legendary Thorong La Pass (5,416m).`,
    highlights: [
      'Summit Pisang Peak (6,091m) — the Pyramid Summit',
      'Cross the world\'s highest pass — Thorong La (5,416m)',
      'The "Great Barrier" panorama of the Annapurna Massif',
      'Trek beneath the awe-inspiring Paungda Danda (The "Great Wall of Annapurna")',
      'Explore medieval Tibetan villages — Upper Pisang, Ngawal, and Braka',
      'High-altitude desert transition through Mustang',
      'Visit the 108 sprouts of sacred Muktinath Temple',
      'The deepest gorge in the world — Kali Gandaki',
      'End with sunrise at Poon Hill (3,210m)',
    ],
    overview: [
      `The Pisang Peak and Thorong La Pass expedition is a comprehensive high-altitude odyssey that combines a challenging 6,000m summit with the world's most iconic mountain crossing. The journey begins with a scenic drive to the Marsyangdi Valley, steadily ascending toward both objectives: Pisang Peak (6,091m) and Thorong La Pass (5,416m).`,
      `Success depends on elite-level physical conditioning, focusing on cardiovascular capacity and weighted hiking at least 4 months before departure. Terrain transitions from lush forests to steep snow slopes requiring crampons, ice axes, and fixed ropes. Required permits include the NMA climbing permit for Pisang Peak, ACAP permit, and TIMS card.`,
      `The trek reaches its dual climaxes at the summit of Pisang Peak (6,091m) and the prayer-flag-strewn crest of Thorong La Pass (5,416m), offering breathtaking panoramas from Manaslu to Dhaulagiri. This is a profound crossing of the Great Himalayan Range, balancing a 6,000m peak with deep cultural and spiritual discovery.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Preparation',                        description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Drive to Syange (1,100 m)',                                        description: '7–8 hours drive. Private 4WD vehicle.' },
      { day: 4,  title: 'Trek to Tal (1,700 m)',                                            description: '5–6 hours. Cross suspension bridges and waterfalls.' },
      { day: 5,  title: 'Trek to Dharapani/Danakyu (1,860 m)',                              description: '5–6 hours. Where Annapurna meets Manaslu Circuit.' },
      { day: 6,  title: 'Trek to Chame (2,670 m)',                                          description: '5–6 hours. Administrative hub of Manang district.' },
      { day: 7,  title: 'Trek to Pisang Village (3,300 m)',                                 description: '5–6 hours. Views of Paungda Danda.' },
      { day: 8,  title: 'Pisang Village Exploration & Acclimatization',                     description: 'Visit monastery and enjoy Annapurna views.' },
      { day: 9,  title: 'Trek to Pisang Peak Base Camp (4,380 m)',                          description: '6–7 hours. Steep climb through alpine pastures.' },
      { day: 10, title: 'Move to Pisang Peak High Camp (5,450 m)',                          description: '6–7 hours. Demanding carry up scree and rocky terrain.' },
      { day: 11, title: 'High Camp Rest & Technical Climbing Practice',                     description: 'Practice jumars and rappelling on snow slopes.' },
      { day: 12, title: 'Summit Day: Pisang Peak (6,091m) & Return to Base Camp',          description: '9–10 hours. 2:00 AM alpine start.' },
      { day: 13, title: 'Climbing Weather Contingency Day',                                 description: 'Reserve day for secondary summit window.' },
      { day: 14, title: 'Trek to Pisang Village (3,300 m)',                                 description: '5–6 hours. Return to guesthouse comfort.' },
      { day: 15, title: 'Trek to Manang (3,540 m)',                                         description: '6–7 hours. Take upper route via Ghyaru and Ngawal.' },
      { day: 16, title: 'Trek to Yak Kharka (4,050 m)',                                     description: '5–6 hours. Climb through juniper bushes.' },
      { day: 17, title: 'Trek to Thorong Phedi (4,450 m)',                                  description: '5–6 hours. Base settlement at foot of pass.' },
      { day: 18, title: 'Cross Thorong La Pass (5,416m) & Trek to Muktinath (3,760m)',      description: '7–8 hours. 4:00 AM start. Prayer flags at summit.' },
      { day: 19, title: 'Trek to Jomsom (2,720 m)',                                         description: '5–6 hours. Desert landscapes of Lower Mustang.' },
      { day: 20, title: 'Fly to Pokhara (900 m)',                                           description: '30-minute scenic flight through the gorge.' },
      { day: 21, title: 'Drive to Kathmandu (1,400 m)',                                     description: '7–8 hours. Tourist bus through foothills.' },
      { day: 22, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Pisang Peak & Thorong La',
  },

  'tent-peak-abc': {
    title: 'Tent Peak Climbing with Annapurna Base Camp',
    duration: '19 Days',
    difficulty: 'Challenging / Alpine',
    elevation: '5,663 m / 18,579 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Climbing',
    accommodation: 'Tea House / Hotel & Base Camp (Mini Tented Village)',
    heroImages: ['/assets/images/tent-peak.jpg', '/assets/images/annapurna-base-camp.jpg', '/assets/images/poon-hill.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Tent Peak Climbing with ABC', href: '#' },
    ],
    description: `Where earth meets sky: trace the sacred trails of the Annapurna Sanctuary to a triumphant summit of Tharpu Chuli (Tent Peak). This 19-day expedition combines a trek into the heart of the Annapurna Sanctuary with a technical ascent of 5,663m.`,
    highlights: [
      'Summit Tharpu Chuli (Tent Peak) at 5,663m',
      'The 360° Amphitheater View of Annapurna I (8,091m), Annapurna South, and sacred Machhapuchhre (Fishtail)',
      'Visit Annapurna Base Camp (4,130m) — the natural amphitheater of giants',
      'The legendary Poon Hill sunrise (3,210m)',
      'Sacred Machhapuchhre (Fishtail Peak) — untouched and revered',
      'Gurung heritage and culture in traditional villages like Ghandruk and Chhomrong',
      'Lush rhododendron forests in full bloom (spring season)',
      'Relax in Jhinu Danda\'s natural hot springs',
    ],
    overview: [
      `The Tent Peak Climbing with Annapurna Base Camp expedition is a spectacular high-altitude journey that combines a trek into the heart of the Annapurna Sanctuary with a technical ascent of Tharpu Chuli (5,663m). The adventure begins with a scenic trek through rhododendron forests to Machhapuchhre Base Camp before reaching the natural amphitheater of Annapurna Base Camp (4,130m).`,
      `Success depends on solid physical fitness and willingness to engage with basic mountaineering techniques. The ascent involves navigating a rubble-covered glacier and climbing steep snow slopes of 45-50 degrees, requiring crampons, an ice axe, and fixed ropes. Required permits include ACAP permit, TIMS card, and NMA climbing permit.`,
      `The expedition reaches its dramatic climax at the summit of Tent Peak (5,663m), offering a unique vantage point from the center of the sanctuary with views of Annapurna South, Hiunchuli, and Machhapuchhre. This is a profound journey through a sacred landscape, ending with natural hot springs at Jhinu Danda.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Preparation',                        description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Drive to Pokhara (900 m)',                                         description: '7–8 hours drive. Tourist bus to lakeside city.' },
      { day: 4,  title: 'Drive to Tikhedhunga & Trek to Ulleri (2,070 m)',                  description: '3-4 hours drive, 2-3 hours trek up 3,000 stone steps.' },
      { day: 5,  title: 'Trek to Ghorepani (2,840 m)',                                      description: '5–6 hours through dense rhododendron forests.' },
      { day: 6,  title: 'Sunrise Hike to Poon Hill (3,210m) & Trek to Tadapani',           description: '1-2 hours sunrise hike, 6-7 hours trek.' },
      { day: 7,  title: 'Trek to Chomrong (2,140 m)',                                       description: '5–6 hours. Gurung village beneath Machhapuchhre.' },
      { day: 8,  title: 'Trek to Dovan (2,600 m)',                                          description: '5–6 hours through bamboo and oak forests.' },
      { day: 9,  title: 'Trek to Deurali (3,230 m)',                                        description: '4–5 hours. Sub-alpine valley near glacial riverbanks.' },
      { day: 10, title: 'Trek to Annapurna Base Camp (4,130 m)',                            description: '5–6 hours. 360° wall of 7,000-8,000m peaks.' },
      { day: 11, title: 'Trek to Tent Peak Base Camp (4,400 m)',                            description: '5–6 hours. Navigate South Annapurna Glacier moraine.' },
      { day: 12, title: 'Move to High Camp (5,000 m)',                                      description: '3–4 hours. Steep ridge line over loose rock.' },
      { day: 13, title: 'Summit Day: Tent Peak (5,695m) & Return to Base Camp',             description: '9–10 hours. 1:00-2:00 AM alpine start.' },
      { day: 14, title: 'Trek to Deurali (3,230 m)',                                        description: '6–7 hours. Re-cross South Annapurna Glacier.' },
      { day: 15, title: 'Trek to Chomrong (2,140 m)',                                       description: '6–7 hours. Descend through bamboo forests.' },
      { day: 16, title: 'Trek to Ghandruk (1,940 m)',                                       description: '5–6 hours. Traditional Gurung village.' },
      { day: 17, title: 'Drive to Pokhara via Siwai',                                       description: '3-4 hours drive. Lakeside hotel celebration.' },
      { day: 18, title: 'Drive to Kathmandu (1,400 m)',                                     description: '7–8 hours. Tourist bus to Kathmandu Valley.' },
      { day: 19, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Tent Peak with ABC',
  },

  'everest-base-camp-lobuche-east': {
    title: 'Everest Base Camp & Lobuche East',
    duration: '19 Days',
    difficulty: 'Challenging / Semi-Technical',
    elevation: '6,119 m / 20,070 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Strenuous Trekking / Moderate Technical Climbing',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/everest-base-camp.jpg', '/assets/images/lobuche-east.jpg', '/assets/images/khumbu.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Everest Base Camp & Lobuche East', href: '#' },
    ],
    description: `The Khumbu Double Crown: A premier progression from the world's most historic base camp to a 6,000-meter alpine summit. This 19-day expedition combines the legendary Everest Base Camp trek with a technical ascent of Lobuche East (6,119m).`,
    highlights: [
      'Summit Lobuche East at 6,119m — a world-class mountaineering achievement',
      'The Grand Stand of the Giants — panoramic views of Everest, Lhotse, Nuptse, Makalu, Cho Oyu, and Ama Dablam',
      'Visit the world\'s greatest base camp at 5,364m',
      'The masterpiece vantage point of Kala Patthar (5,550m)',
      'Pre-climb glacier training academy',
      'Spiritual sanctuary of Tengboche Monastery (3,867m)',
      'Explore the vibrant Sherpa hub of Namche Bazaar (3,440m)',
    ],
    overview: [
      `The Everest Base Camp and Lobuche East expedition is a prestigious high-altitude challenge that combines the world's most famous trek with a technical 6,000m summit. The journey begins with a flight to Lukla (2,846m) and follows the legendary Khumbu trail toward Everest Base Camp (5,364m) and Kala Patthar (5,545m) before shifting focus to the ultimate objective: the 6,119m summit of Lobuche East.`,
      `Success on this dual-objective mission depends on elite-level physical conditioning, focusing on cardiovascular endurance and lower-body strength at least 4 months before arrival. The terrain transitions from rocky glacial moraines to steep, technical ice and snow sections requiring professional mountaineering boots, crampons, and harness systems. Required permits include the Sagarmatha National Park permit, the Khumbu local permit, and the NMA climbing permit for Lobuche.`,
      `The expedition reaches its dramatic climax at the summit of Lobuche East (6,119m), providing one of the most spectacular vantage points in the world, with a direct line of sight to Everest, Lhotse, Nuptse, and Ama Dablam. This experience bridges the gap between trekking and true mountaineering, connecting the historical legacy of the Everest trail with the physical triumph of a Himalayan peak.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Trek Preparation',                         description: 'Guided tour of historic landmarks, gear check, and welcome dinner.' },
      { day: 3,  title: 'Fly to Lukla & Trek to Phakding (2,610 m)',                        description: '35-minute flight. Trek 3–4 hours downhill to Phakding.' },
      { day: 4,  title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '5–6 hours through pine forests and suspension bridges.' },
      { day: 5,  title: 'Acclimatization Day at Namche Bazaar',                             description: 'Hike to Hotel Everest View (3,962m) for stunning panoramas.' },
      { day: 6,  title: 'Trek to Tengboche Monastery (3,860 m)',                            description: '5–6 hours to the famous ridge-top monastery.' },
      { day: 7,  title: 'Trek to Dingboche (4,410 m)',                                       description: '5–6 hours through alpine villages to Dingboche.' },
      { day: 8,  title: 'Chukhung Valley Day Hike (4,730m) - Acclimatization',              description: '4–5 hours round trip. Views of Island Peak and Lhotse face.' },
      { day: 9,  title: 'Trek to Lobuche (4,930 m)',                                        description: '5–6 hours. Pass the memorial plateau at Chukpo Lari.' },
      { day: 10, title: 'Trek to Everest Base Camp (5,364m) & Return to Gorak Shep',       description: '7–8 hours total. Stand at the foot of the Khumbu Icefall.' },
      { day: 11, title: 'Hike Kala Patthar (5,555m) & Trek to Lobuche',                     description: '5–6 hours. Pre-dawn climb for sunrise over Everest.' },
      { day: 12, title: 'Trek to Lobuche East Base Camp (4,950 m)',                         description: '5–6 hours to tented wilderness camp. Gear inspection.' },
      { day: 13, title: 'Move to Lobuche High Camp (5,400 m)',                              description: 'Short but demanding carry. Crampon and rope technique review.' },
      { day: 14, title: 'Summit Day: Lobuche East (6,119m) & Return to Base Camp',         description: '10–11 hours. 2:00-3:00 AM alpine start. Fixed ropes on headwall.' },
      { day: 15, title: 'Climbing Weather Contingency / Buffer Day',                       description: 'Reserve day for secondary summit window or rest.' },
      { day: 16, title: 'Trek to Pangboche (3,930 m)',                                      description: '6–7 hours. Rewarding descent from high altitudes.' },
      { day: 17, title: 'Trek to Namche Bazaar (3,440 m)',                                  description: '6–7 hours. Celebratory meal in the Sherpa capital.' },
      { day: 18, title: 'Trek to Lukla (2,840 m)',                                          description: '5–6 hours. Final day on the trail.' },
      { day: 19, title: 'Fly Back to Kathmandu',                                            description: 'Morning flight back to Kathmandu. Farewell dinner.' },
      { day: 20, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'EBC & Lobuche East',
  },

  'pisang-peak': {
    title: 'Pisang Peak Climbing',
    duration: '15 Days',
    difficulty: 'Challenging / Non-Technical',
    elevation: '6,091 m / 19,980 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Moderate Climbing',
    accommodation: 'Tea House / Hotel & Base Camp (Mini Tented Village)',
    heroImages: ['/assets/images/pisang-peak.jpg', '/assets/images/annapurna-circuit.jpg', '/assets/images/manang.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Pisang Peak Climbing', href: '#' },
    ],
    description: `One of the most accessible 6,000m summits in the Annapurna region, Pisang Peak offers the perfect "sightseeing peak" for aspiring mountaineers. This 15-day expedition follows the scenic Annapurna Circuit trail to the 6,091m summit.`,
    highlights: [
      'Summit Pisang Peak (6,091m) — the Pyramid Summit of the Annapurna region',
      'The "Double High" Experience — unparalleled mountain views',
      'The Gates to Heaven (Swarga Dwari)',
      'A bird\'s-eye view of the entire Annapurna Massif',
      'Upper Pisang cultural immersion in traditional Tibetan-Buddhist villages',
      'Sacred Muktinath Temple — a pilgrimage site for Hindus and Buddhists',
      'The high-altitude desert of Mustang',
    ],
    overview: [
      `The Pisang Peak Climbing expedition is widely considered one of the most accessible 6,000m summits in the Annapurna region, making it an ideal "sightseeing peak" for aspiring mountaineers. The journey typically begins with a drive to Chame (2,670m) and follows the scenic Annapurna Circuit trail toward the 6,091m summit.`,
      `Success on this climb depends on solid cardiovascular fitness and lower-body endurance, with training recommended to start at least 3 months before departure. While the route is categorized as non-technical, the final ascent involves a steep snow headwall of approximately 45-50 degrees, requiring crampons, an ice axe, and fixed ropes. Required permits include the NMA climbing permit, ACAP permit, and TIMS card.`,
      `The trek reaches its rewarding climax at the summit of Pisang Peak (6,091m), where climbers are treated to a spectacular 360-degree panorama of the Damodar Himalaya and the Annapurna range. The final leg follows a reflective journey over Thorong La Pass (5,416m) and down to the sacred temples of Muktinath.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,350 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Preparation',                        description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Drive Kathmandu to Dharapani (1,860 m)',                           description: '8–10 hours drive. Private 4WD alongside Trishuli River.' },
      { day: 4,  title: 'Trek Dharapani to Chame (2,670 m)',                                description: '5–6 hours through pine, fir, and rhododendron forests.' },
      { day: 5,  title: 'Trek Chame to Upper Pisang (3,300 m)',                              description: '5–6 hours. Views of Paungda Danda rock face.' },
      { day: 6,  title: 'Acclimatization Day in Upper Pisang',                              description: 'Explore monastery and enjoy views of Annapurna II and III.' },
      { day: 7,  title: 'Trek to Pisang Peak Base Camp (4,380 m)',                          description: '6–7 hours. Steep uphill through alpine pastures.' },
      { day: 8,  title: 'Move to High Camp (5,400 m)',                                      description: '6–7 hours. Demanding carry up steep ridge line.' },
      { day: 9,  title: 'Summit Day: Pisang Peak (6,091m) & Descend to Base Camp',          description: '9–10 hours. 2:00 AM alpine start. Fixed lines on headwall.' },
      { day: 10, title: 'Trek from Base Camp to Manang (3,540 m)',                          description: '6–7 hours. Descent through dry, rain-shadow landscape.' },
      { day: 11, title: 'Trek Manang to Yak Kharka (4,110 m)',                              description: '5–6 hours. Climb through juniper bushes and grazing pastures.' },
      { day: 12, title: 'Trek to Thorong Phedi (4,450 m)',                                  description: '5–6 hours. Base settlement at foot of the high pass.' },
      { day: 13, title: 'Cross Thorong La Pass (5,416m) to Muktinath (3,760m)',             description: '7–8 hours. 4:00 AM start. Prayer flags at summit.' },
      { day: 14, title: 'Drive/Fly to Pokhara & Return to Kathmandu',                       description: 'Morning drive to Jomsom, flight to Pokhara, then to Kathmandu.' },
      { day: 15, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Pisang Peak',
  },

  'yala-peak': {
    title: 'Yala Peak Climbing',
    duration: '14 Days',
    difficulty: 'Challenging',
    elevation: '5,500 m / 18,045 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Climbing',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/yala-peak.jpg', '/assets/images/langtang.jpg', '/assets/images/kyanjin-gompa.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Yala Peak Climbing', href: '#' },
    ],
    description: `The perfect entry-level peak climbing experience in the Langtang region. Yala Peak (5,500m) offers a scenic, direct introduction to Himalayan glacier mountaineering with stunning views of Shishapangma, the only 8,000m peak completely in Tibet.`,
    highlights: [
      'Summit Yala Peak (5,500m) — a gateway to Himalayan mountaineering',
      'The staggering Shishapangma horizon — views of the Tibetan 8,000m peak',
      'Deep Tamang cultural heritage integration',
      'The sacred sanctuary of Kyanjin Gompa (3,830m)',
      'The rushing Langtang Khola gorge',
      'Spectacular views of Langtang Lirung (7,227m) and Dorje Lakpa',
      'Optional hike to Tserko Ri (4,984m) for sweeping panoramas',
    ],
    overview: [
      `The Yala Peak Climbing expedition is an ideal entry-level mountaineering experience that requires good physical fitness and a spirit for adventure. The journey begins with a scenic drive from Kathmandu to Syabrubesi (1,500m) and winds through beautiful Langtang National Park toward the summit of Yala Peak at 5,520m.`,
      `Success at this peak depends on consistent cardiovascular training and hiking experience at least 2 months before departure. The terrain transitions from lush rhododendron forests to rocky moraines and snow-covered slopes, requiring sturdy trekking boots, crampons, and a versatile layering system. Required permits include the Langtang National Park entry permit and TIMS card.`,
      `The trek reaches its rewarding climax at the summit of Yala Peak (5,520m), where climbers are treated to a spectacular panorama of Shishapangma and the sprawling Ganesh Himal range. This is a perfect introduction to Himalayan mountaineering, connecting the vibrant culture of the Langtang Valley to pristine, high-altitude wilderness.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Preparation',                        description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Drive to Syabru Besi (1,462 m)',                                   description: '7–8 hours drive through Langtang National Park.' },
      { day: 4,  title: 'Trek to Lama Hotel (2,500 m)',                                     description: '5–6 hours through dense forests of oak and bamboo.' },
      { day: 5,  title: 'Trek to Langtang Village (3,400 m)',                               description: '5–6 hours. First glimpses of Langtang Lirung.' },
      { day: 6,  title: 'Trek to Kyanjin Gompa (3,830 m)',                                  description: '4–5 hours. Surrounded by an amphitheater of snowy peaks.' },
      { day: 7,  title: 'Kyanjin Gompa Exploration & Acclimatization',                      description: 'Hike Kyanjin Ri (4,773m) or Tserko Ri (4,984m).' },
      { day: 8,  title: 'Trek to Yala Peak Base Camp (4,500 m)',                            description: '5–6 hours. Steep climb along rugged ridge line.' },
      { day: 9,  title: 'Summit Day: Yala Peak (5,500m) & Return to Kyanjin Gompa',        description: '8–9 hours. 2:00 AM alpine start. Non-technical but demanding.' },
      { day: 10, title: 'Climbing Weather Contingency Day',                                 description: 'Reserve day for secondary summit window or rest.' },
      { day: 11, title: 'Trek back to Lama Hotel (2,500 m)',                                description: '5–6 hours. Long, rewarding descent down valley.' },
      { day: 12, title: 'Trek to Syabru Besi (1,462 m)',                                    description: '6–7 hours. Final day on the trail.' },
      { day: 13, title: 'Drive back to Kathmandu (1,400 m)',                                description: '7–8 hours drive. Farewell dinner.' },
      { day: 14, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Yala Peak',
  },

  'everest-high-passes-island-peak': {
    title: 'Everest High Passes & Island Peak',
    duration: '24 Days',
    difficulty: 'Challenging / Semi-Technical',
    elevation: '6,187 m / 20,299 ft',
    season: 'Feb–Jun & Sep–Dec',
    groupSize: '2 or more',
    activity: 'Multi-Activity (Trekking & Climbing)',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/everest-high-passes.jpg', '/assets/images/island-peak-summit.jpg', '/assets/images/gokyo-lakes.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Everest High Passes & Island Peak', href: '#' },
    ],
    description: `The ultimate Khumbu Grand Slam: three 5,000-meter passes and a 6,000-meter summit achievement. This 24-day expedition combines the legendary Three High Passes—Renjo La, Cho La, and Kongma La—with a technical ascent of Island Peak (6,189m).`,
    highlights: [
      'Complete the Three High Passes trilogy: Renjo La (5,360m), Cho La (5,420m), and Kongma La (5,535m)',
      'Summit Island Peak (Imja Tse) at 6,189m',
      'Photography across the region with guaranteed ascents of Gokyo Ri (5,357m) and Kala Patthar (5,550m)',
      'Visit Everest Base Camp (5,364m)',
      'The shimmering turquoise Gokyo Lakes',
      'Traverse active moving glaciers including the Ngozumpa Glacier',
      'Front-row view of Lhotse\'s massive south face from the summit ridge',
    ],
    overview: [
      `The Everest High Passes and Island Peak Expedition is the definitive alpine challenge in the Khumbu region, masterfully combining a massive high-altitude circuit with a technical mountaineering summit. The journey targets the completion of the legendary Three High Passes—Renjo La (5,360m), Cho La (5,420m), and Kongma La (5,535m)—alongside Everest Base Camp (5,364m).`,
      `Success on this demanding itinerary requires exceptional physical preparation and mental toughness, with training focused on weighted uphill endurance initiated at least 4 to 6 months before departure. Terrain includes shifting glacial moraines, steep ice-glazed passes, and vertical headwalls requiring crampons, ice axe, and fixed-rope jumar ascents. Required permits include Sagarmatha National Park permit, Khumbu local permit, and NMA peak climbing permit.`,
      `The expedition reaches its grand climax on the knife-edge summit ridge of Island Peak (6,189m), offering a surreal, front-row view of Lhotse's massive south face. The transition from teahouse trekking to full tented camping at Island Peak Base Camp marks the final shift into true mountaineering.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Trek Preparation',                         description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Fly to Lukla & Trek to Phakding (2,610 m)',                        description: '3–4 hours gentle trek to Phakding.' },
      { day: 4,  title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '5–6 hours. Steep climb to the Sherpa capital.' },
      { day: 5,  title: 'Namche Bazaar Rest Day (Acclimatization)',                         description: 'Hike to Hotel Everest View (3,880m).' },
      { day: 6,  title: 'Trek to Phortse Tenga (3,680 m)',                                   description: '5–6 hours. Leave main trail to quiet valley.' },
      { day: 7,  title: 'Trek to Machhermo (4,470 m)',                                       description: '5–6 hours. Views of Cho Oyu.' },
      { day: 8,  title: 'Trek to Gokyo Lakes (4,800 m)',                                     description: '5–6 hours. Walk alongside pristine glacial lakes.' },
      { day: 9,  title: 'Hike Gokyo Ri (5,483m) & Return to Gokyo',                         description: '5–6 hours. Panoramic views of four 8,000m peaks.' },
      { day: 10, title: 'Trek to Thangnak (4,500 m)',                                        description: '4–5 hours. Traverse Ngozumpa Glacier moraine.' },
      { day: 11, title: 'Cross Cho La Pass (5,368m) & Trek to Dzongla (4,830m)',            description: '7–8 hours. Pre-dawn start over icy glacier plateau.' },
      { day: 12, title: 'Trek to Lobuche (4,910 m)',                                        description: '4–5 hours. Panoramic trail above Cholaste Lake.' },
      { day: 13, title: 'Hike Kala Patthar (5,555m) & Return to Gorak Shep',                description: '7–8 hours. Sunset views over Mount Everest.' },
      { day: 14, title: 'Visit Everest Base Camp (5,364m) & Return to Lobuche',             description: '8–9 hours. Explore historic site at Khumbu Icefall.' },
      { day: 15, title: 'Cross Kongma La Pass (5,535m) & Trek to Chukhung',                 description: '8–9 hours. The highest of the three passes.' },
      { day: 16, title: 'Trek to Island Peak Base Camp (5,240 m)',                          description: '4–5 hours. Along Imja Glacier lateral moraine.' },
      { day: 17, title: 'Base Camp Rest & Skills Training',                                 description: 'Practice fixed-rope techniques and gear check.' },
      { day: 18, title: 'Summit Island Peak (6,187m) & Return to Chukhung',                 description: '9–10 hours. Midnight start. Fixed-line headwall.' },
      { day: 19, title: 'Climbing Weather Contingency Day',                                 description: 'Reserve day for secondary summit window.' },
      { day: 20, title: 'Trek to Tengboche (3,860 m)',                                      description: '6–7 hours. Descend through Imja Valley.' },
      { day: 21, title: 'Trek to Namche Bazaar via Khumjung',                               description: '5–6 hours. Visit Khumjung monastery.' },
      { day: 22, title: 'Trek to Lukla (2,840 m)',                                          description: '6–7 hours. Final day on the trail.' },
      { day: 23, title: 'Fly Back to Kathmandu',                                            description: 'Morning flight back to Kathmandu.' },
      { day: 24, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'High Passes & Island Peak',
  },

  'ama-dablam': {
    title: 'Ama Dablam Expedition',
    duration: '29 Days',
    difficulty: 'Technical / Advanced',
    elevation: '6,812 m / 22,349 ft',
    season: 'Spring (Apr–May) & Autumn (Oct–Nov)',
    groupSize: '2 or more',
    activity: 'Technical Mountaineering (Rock, Ice & Mixed)',
    accommodation: 'Tea House / Hotel & High Camps (Tented)',
    heroImages: ['/assets/images/ama-dablam.jpg', '/assets/images/ama-dablam-summit.jpg', '/assets/images/khumbu.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Ama Dablam Expedition', href: '#' },
    ],
    description: `The world's most aesthetic summit (6,812m) and a definitive "rite of passage" for experienced alpinists. Ama Dablam's iconic pyramid shape requires mastery of technical rock, ice, and mixed-terrain climbing on the legendary Southwest Ridge.`,
    highlights: [
      'Summit Ama Dablam (6,812m) — one of the world\'s most beautiful mountains',
      'The iconic "Mother\'s Necklace" — witness the massive hanging glacier that gives the mountain its name',
      'The legendary Yellow Tower — a technical rock climbing challenge',
      'Spectacular "bird\'s-eye" high camps with unrivaled 360-degree views',
      'Unrivaled 360-degree views of Everest, Lhotse, and Makalu',
      'Cultural trek through the Khumbu to Base Camp',
      'A "Grail" for seasoned climbers seeking the ultimate Himalayan test',
    ],
    overview: [
      `The Ama Dablam Expedition is a world-renowned mountaineering challenge that stands as a definitive "rite of passage" for experienced alpinists. Rising to 6,812m, the mountain's iconic pyramid shape requires mastery of technical rock, ice, and mixed-terrain climbing. The journey begins with a flight to Lukla and follows the classic Khumbu trail before diverting to Ama Dablam Base Camp.`,
      `Success on Ama Dablam depends on advanced technical proficiency, including comfort on fixed ropes, vertical rock sections (up to 5.7 grade), and steep ice pitches. Climbers should initiate an elite-level training program at least 6 months prior, focusing on upper-body strength, precision footwork, and sustained cardiovascular power. A specific climbing permit from the Department of Tourism, plus Sagarmatha National Park and Khumbu permits, is required.`,
      `The expedition reaches its breathtaking climax at the sharp summit of Ama Dablam (6,812m), providing an unparalleled, close-up panorama of Everest, Lhotse, and Makalu. Standing on the summit demonstrates technical composure and climbing precision in one of the world's most spectacular alpine arenas.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Briefing',                           description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Final Preparation & Permit Day in Kathmandu',                      description: 'Permit processing and last-minute equipment rentals.' },
      { day: 4,  title: 'Fly to Lukla & Trek to Phakding (2,610 m)',                        description: '3–4 hours trek. Meet your climbing crew.' },
      { day: 5,  title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '5–6 hours. Cross the famous Hillary Suspension Bridge.' },
      { day: 6,  title: 'Namche Rest Day (Acclimatization)',                                description: 'Hike to Hotel Everest View (3,880m). Views of Ama Dablam.' },
      { day: 7,  title: 'Trek to Tengboche Monastery (3,860 m)',                            description: '5–6 hours. Iconic ridge-top monastery.' },
      { day: 8,  title: 'Trek to Pangboche (3,930 m)',                                      description: '2–3 hours. Home to the oldest monastery in Khumbu.' },
      { day: 9,  title: 'Trek to Ama Dablam Base Camp (4,600 m)',                           description: '5–6 hours. Private kitchen and tented camp established.' },
      { day: 10, title: 'Base Camp Rest & Acclimatization',                                 description: 'Gear sorting, fitting, and traditional Puja ceremony.' },
      { day: 11, title: 'Ama Dablam Climbing Period — Rotation 1 to Camp 1 (5,700m)',       description: 'Technical rock and ice climbing on Southwest Ridge.' },
      { day: 12, title: 'Climbing Period — Return to Base Camp',                           description: 'Descend to Base Camp for rest and recovery.' },
      { day: 13, title: 'Climbing Period — Rest Day at Base Camp',                         description: 'Hydration, gear prep, and route strategy.' },
      { day: 14, title: 'Climbing Period — Rotation to Camp 2 (5,900m)',                    description: 'Move higher on the mountain. Establish Camp 2.' },
      { day: 15, title: 'Climbing Period — Return to Base Camp',                           description: 'Descend for final rest before summit push.' },
      { day: 16, title: 'Climbing Period — Rest Day at Base Camp',                         description: 'Final preparations and weather assessment.' },
      { day: 17, title: 'Climbing Period — Move to Camp 1',                                 description: 'Begin summit rotation. Sleep at Camp 1.' },
      { day: 18, title: 'Climbing Period — Move to Camp 2',                                 description: 'Ascend to high camp for summit positioning.' },
      { day: 19, title: 'Summit Push — Ama Dablam (6,812m) & Descend to Camp 2',           description: 'Summit via Yellow Tower and exposed ridges.' },
      { day: 20, title: 'Climbing Period — Descend to Base Camp',                          description: 'Return to Base Camp after successful summit.' },
      { day: 21, title: 'Weather Contingency / Reserve Day',                                description: 'Built-in buffer for summit window.' },
      { day: 22, title: 'Weather Contingency / Reserve Day',                                description: 'Additional buffer for mountain conditions.' },
      { day: 23, title: 'Weather Contingency / Reserve Day',                                description: 'Final reserve day for summit attempt.' },
      { day: 24, title: 'Trek to Namche Bazaar (3,440 m)',                                  description: '6–7 hours. Say goodbye to the mountain.' },
      { day: 25, title: 'Trek to Lukla (2,840 m)',                                          description: '6–7 hours. Celebrate with your crew.' },
      { day: 26, title: 'Fly to Kathmandu',                                                 description: 'Morning flight back to Kathmandu.' },
      { day: 27, title: 'Reserve Day in Kathmandu',                                         description: 'Rest, shopping, and relaxation.' },
      { day: 28, title: 'Departure',                                                        description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Ama Dablam',
  },

  'mera-peak': {
    title: 'Mera Peak Climbing',
    duration: '20 Days',
    difficulty: 'Challenging / Semi-Technical',
    elevation: '6,470 m / 21,227 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Climbing',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/mera-peak.jpg', '/assets/images/hinku-valley.jpg', '/assets/images/mera-summit.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Mera Peak Climbing', href: '#' },
    ],
    description: `The roof of trekking peaks: the ultimate high-altitude walking expedition across hidden valleys and wild glacial plateaus. Mera Peak (6,470m) stands as the highest official "trekking peak" in Nepal, offering unparalleled panoramic views of five 8,000-meter peaks.`,
    highlights: [
      'Summit the highest trekking peak in Nepal at 6,470m',
      'The five-8,000er summit masterpiece — views of Everest, Lhotse, Cho Oyu, Makalu, and Kanchenjunga',
      'The wild, unspoiled Hinku Valley entry —远离 crowded EBC trail',
      'Pristine high camp staging at 5,780m',
      'Gradual, foot-safe glacier march suitable for novice climbers',
      'Deeply immersive wilderness approach through Panggom, Ramailo Danda, and Chhatra Khola',
      'Visit century-old Buddhist stupas like Lungsumbga Gompa',
    ],
    overview: [
      `Mera Peak (6,476m) stands crowned as the highest official "trekking peak" in Nepal, offering an unparalleled introductory mountaineering expedition into the spectacular Mahalangur section of the Himalayas. Situated on the edge of the pristine Hinku Valley, this expedition is highly sought after by ambitious trekkers and novice climbers looking to transition into high-altitude alpine mountaineering.`,
      `While classified as a non-technical "walk-up" peak, achieving success on Mera Peak demands excellent physical fitness. The approach requires navigating extensive, heavily crevassed high-altitude glaciers using crampons, an ice axe, and fixed-rope team travel. Required permits include the NMA Mera Peak Climbing Permit, Makalu Barun National Park Entry Permit, and Khumbu Pasang Lhamu Rural Municipality Permit.`,
      `The expedition reaches its breathtaking climax on the small, snow-dome summit of Mera Peak, rewarding climbers with what is widely considered the finest panoramic viewpoint in the entire Himalaya — an unobstructed view of five of the world's fourteen 8,000-meter peaks simultaneously.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Preparation',                        description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Fly to Lukla & Trek to Paiya/Chutok (2,800 m)',                    description: '3–4 hours. Leave main trail to remote farmlands.' },
      { day: 4,  title: 'Trek to Pangkongma (2,900 m)',                                     description: '6–7 hours. Cross Khari La pass.' },
      { day: 5,  title: 'Trek to Nashing Dingma (2,963 m)',                                 description: '6–7 hours. Cross Pangkongma La pass.' },
      { day: 6,  title: 'Trek to Chholem Kharka (3,600 m)',                                 description: '6–7 hours. Summer yak grazing pastures.' },
      { day: 7,  title: 'Trek to Khola Kharka (4,270 m)',                                   description: '6–7 hours. Cross Panch Pokhari pass.' },
      { day: 8,  title: 'Trek to Kothe (3,600 m)',                                          description: '6–7 hours. Rejoin main Hinku Valley trail.' },
      { day: 9,  title: 'Trek to Tangnag (4,350 m)',                                        description: '6–7 hours. Visit 200-year-old Lungsumbga Gompa.' },
      { day: 10, title: 'Tangnag Rest Day (Acclimatization)',                               description: 'Hike toward Sabai Tsho glacial lake.' },
      { day: 11, title: 'Trek to Khare (4,900 m)',                                          description: '4–5 hours. Main alpine base for Mera teams.' },
      { day: 12, title: 'Khare Rest & Technical Climbing Practice',                        description: 'Fit double boots, practice jumar ascents.' },
      { day: 13, title: 'Trek to Mera High Camp (5,800 m)',                                 description: '7–8 hours. Snow climb across Mera Glacier.' },
      { day: 14, title: 'Summit Day: Mera Peak (6,470m) & Return to Khare',                description: '10–15 hours. 1:00-2:00 AM alpine start.' },
      { day: 15, title: 'Climbing Weather Contingency Day',                                 description: 'Reserve day for secondary summit window.' },
      { day: 16, title: 'Trek to Kothe (3,600 m)',                                          description: '6–7 hours. Rewarding descent.' },
      { day: 17, title: 'Trek to Thuli Kharka (4,200 m)',                                   description: '6–7 hours. High-perched settlement.' },
      { day: 18, title: 'Trek to Lukla via Zatrwa La Pass (4,610m)',                        description: '7–8 hours. Final pass crossing.' },
      { day: 19, title: 'Fly Back to Kathmandu',                                            description: 'Morning flight back to Kathmandu.' },
      { day: 20, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Mera Peak',
  },

  'pisang-peak-thorong-la': {
    title: 'Pisang Peak & Thorung La Pass',
    duration: '22 Days',
    difficulty: 'Strenuous / Semi-Technical',
    elevation: '6,091 m / 19,980 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Strenuous Trekking / Technical (Snow & Ice)',
    accommodation: 'Tea House / Hotel & Base Camp (Mini Tented Village)',
    heroImages: ['/assets/images/pisang-peak.jpg', '/assets/images/thorong-la.jpg', '/assets/images/annapurna-circuit.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Pisang Peak & Thorung La Pass', href: '#' },
    ],
    description: `Follow the Marsyangdi River to the stars, standing atop Pisang Peak for a bird's-eye view before crossing the world's most famous pass. This 22-day expedition combines a technical 6,000m summit with the legendary Thorong La Pass (5,416m).`,
    highlights: [
      'Summit Pisang Peak (6,091m) — the Pyramid Summit',
      'Cross the world\'s highest pass — Thorong La (5,416m)',
      'The "Great Barrier" panorama of the Annapurna Massif',
      'Trek beneath the awe-inspiring Paungda Danda (The "Great Wall of Annapurna")',
      'Explore medieval Tibetan villages — Upper Pisang, Ngawal, and Braka',
      'High-altitude desert transition through Mustang',
      'Visit the 108 sprouts of sacred Muktinath Temple',
      'The deepest gorge in the world — Kali Gandaki',
      'End with sunrise at Poon Hill (3,210m)',
    ],
    overview: [
      `The Pisang Peak and Thorong La Pass expedition is a comprehensive high-altitude odyssey that combines a challenging 6,000m summit with the world's most iconic mountain crossing. The journey begins with a scenic drive to the Marsyangdi Valley, steadily ascending toward both objectives: Pisang Peak (6,091m) and Thorong La Pass (5,416m).`,
      `Success depends on elite-level physical conditioning, focusing on cardiovascular capacity and weighted hiking at least 4 months before departure. Terrain transitions from lush forests to steep snow slopes requiring crampons, ice axes, and fixed ropes. Required permits include the NMA climbing permit for Pisang Peak, ACAP permit, and TIMS card.`,
      `The trek reaches its dual climaxes at the summit of Pisang Peak (6,091m) and the prayer-flag-strewn crest of Thorong La Pass (5,416m), offering breathtaking panoramas from Manaslu to Dhaulagiri. This is a profound crossing of the Great Himalayan Range, balancing a 6,000m peak with deep cultural and spiritual discovery.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Preparation',                        description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Drive to Syange (1,100 m)',                                        description: '7–8 hours drive. Private 4WD vehicle.' },
      { day: 4,  title: 'Trek to Tal (1,700 m)',                                            description: '5–6 hours. Cross suspension bridges and waterfalls.' },
      { day: 5,  title: 'Trek to Dharapani/Danakyu (1,860 m)',                              description: '5–6 hours. Where Annapurna meets Manaslu Circuit.' },
      { day: 6,  title: 'Trek to Chame (2,670 m)',                                          description: '5–6 hours. Administrative hub of Manang district.' },
      { day: 7,  title: 'Trek to Pisang Village (3,300 m)',                                 description: '5–6 hours. Views of Paungda Danda.' },
      { day: 8,  title: 'Pisang Village Exploration & Acclimatization',                     description: 'Visit monastery and enjoy Annapurna views.' },
      { day: 9,  title: 'Trek to Pisang Peak Base Camp (4,380 m)',                          description: '6–7 hours. Steep climb through alpine pastures.' },
      { day: 10, title: 'Move to Pisang Peak High Camp (5,450 m)',                          description: '6–7 hours. Demanding carry up scree and rocky terrain.' },
      { day: 11, title: 'High Camp Rest & Technical Climbing Practice',                     description: 'Practice jumars and rappelling on snow slopes.' },
      { day: 12, title: 'Summit Day: Pisang Peak (6,091m) & Return to Base Camp',          description: '9–10 hours. 2:00 AM alpine start.' },
      { day: 13, title: 'Climbing Weather Contingency Day',                                 description: 'Reserve day for secondary summit window.' },
      { day: 14, title: 'Trek to Pisang Village (3,300 m)',                                 description: '5–6 hours. Return to guesthouse comfort.' },
      { day: 15, title: 'Trek to Manang (3,540 m)',                                         description: '6–7 hours. Take upper route via Ghyaru and Ngawal.' },
      { day: 16, title: 'Trek to Yak Kharka (4,050 m)',                                     description: '5–6 hours. Climb through juniper bushes.' },
      { day: 17, title: 'Trek to Thorong Phedi (4,450 m)',                                  description: '5–6 hours. Base settlement at foot of pass.' },
      { day: 18, title: 'Cross Thorong La Pass (5,416m) & Trek to Muktinath (3,760m)',      description: '7–8 hours. 4:00 AM start. Prayer flags at summit.' },
      { day: 19, title: 'Trek to Jomsom (2,720 m)',                                         description: '5–6 hours. Desert landscapes of Lower Mustang.' },
      { day: 20, title: 'Fly to Pokhara (900 m)',                                           description: '30-minute scenic flight through the gorge.' },
      { day: 21, title: 'Drive to Kathmandu (1,400 m)',                                     description: '7–8 hours. Tourist bus through foothills.' },
      { day: 22, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Pisang Peak & Thorong La',
  },

  'tent-peak-abc': {
    title: 'Tent Peak Climbing with Annapurna Base Camp',
    duration: '19 Days',
    difficulty: 'Challenging / Alpine',
    elevation: '5,663 m / 18,579 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Climbing',
    accommodation: 'Tea House / Hotel & Base Camp (Mini Tented Village)',
    heroImages: ['/assets/images/tent-peak.jpg', '/assets/images/annapurna-base-camp.jpg', '/assets/images/poon-hill.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Tent Peak Climbing with ABC', href: '#' },
    ],
    description: `Where earth meets sky: trace the sacred trails of the Annapurna Sanctuary to a triumphant summit of Tharpu Chuli (Tent Peak). This 19-day expedition combines a trek into the heart of the Annapurna Sanctuary with a technical ascent of 5,663m.`,
    highlights: [
      'Summit Tharpu Chuli (Tent Peak) at 5,663m',
      'The 360° Amphitheater View of Annapurna I (8,091m), Annapurna South, and sacred Machhapuchhre (Fishtail)',
      'Visit Annapurna Base Camp (4,130m) — the natural amphitheater of giants',
      'The legendary Poon Hill sunrise (3,210m)',
      'Sacred Machhapuchhre (Fishtail Peak) — untouched and revered',
      'Gurung heritage and culture in traditional villages like Ghandruk and Chhomrong',
      'Lush rhododendron forests in full bloom (spring season)',
      'Relax in Jhinu Danda\'s natural hot springs',
    ],
    overview: [
      `The Tent Peak Climbing with Annapurna Base Camp expedition is a spectacular high-altitude journey that combines a trek into the heart of the Annapurna Sanctuary with a technical ascent of Tharpu Chuli (5,663m). The adventure begins with a scenic trek through rhododendron forests to Machhapuchhre Base Camp before reaching the natural amphitheater of Annapurna Base Camp (4,130m).`,
      `Success depends on solid physical fitness and willingness to engage with basic mountaineering techniques. The ascent involves navigating a rubble-covered glacier and climbing steep snow slopes of 45-50 degrees, requiring crampons, an ice axe, and fixed ropes. Required permits include ACAP permit, TIMS card, and NMA climbing permit.`,
      `The expedition reaches its dramatic climax at the summit of Tent Peak (5,663m), offering a unique vantage point from the center of the sanctuary with views of Annapurna South, Hiunchuli, and Machhapuchhre. This is a profound journey through a sacred landscape, ending with natural hot springs at Jhinu Danda.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and private transfer to your hotel.' },
      { day: 2,  title: 'Kathmandu Sightseeing & Climb Preparation',                        description: 'Guided tour, gear inspection, and welcome dinner.' },
      { day: 3,  title: 'Drive to Pokhara (900 m)',                                         description: '7–8 hours drive. Tourist bus to lakeside city.' },
      { day: 4,  title: 'Drive to Tikhedhunga & Trek to Ulleri (2,070 m)',                  description: '3-4 hours drive, 2-3 hours trek up 3,000 stone steps.' },
      { day: 5,  title: 'Trek to Ghorepani (2,840 m)',                                      description: '5–6 hours through dense rhododendron forests.' },
      { day: 6,  title: 'Sunrise Hike to Poon Hill (3,210m) & Trek to Tadapani',           description: '1-2 hours sunrise hike, 6-7 hours trek.' },
      { day: 7,  title: 'Trek to Chomrong (2,140 m)',                                       description: '5–6 hours. Gurung village beneath Machhapuchhre.' },
      { day: 8,  title: 'Trek to Dovan (2,600 m)',                                          description: '5–6 hours through bamboo and oak forests.' },
      { day: 9,  title: 'Trek to Deurali (3,230 m)',                                        description: '4–5 hours. Sub-alpine valley near glacial riverbanks.' },
      { day: 10, title: 'Trek to Annapurna Base Camp (4,130 m)',                            description: '5–6 hours. 360° wall of 7,000-8,000m peaks.' },
      { day: 11, title: 'Trek to Tent Peak Base Camp (4,400 m)',                            description: '5–6 hours. Navigate South Annapurna Glacier moraine.' },
      { day: 12, title: 'Move to High Camp (5,000 m)',                                      description: '3–4 hours. Steep ridge line over loose rock.' },
      { day: 13, title: 'Summit Day: Tent Peak (5,695m) & Return to Base Camp',             description: '9–10 hours. 1:00-2:00 AM alpine start.' },
      { day: 14, title: 'Trek to Deurali (3,230 m)',                                        description: '6–7 hours. Re-cross South Annapurna Glacier.' },
      { day: 15, title: 'Trek to Chomrong (2,140 m)',                                       description: '6–7 hours. Descend through bamboo forests.' },
      { day: 16, title: 'Trek to Ghandruk (1,940 m)',                                       description: '5–6 hours. Traditional Gurung village.' },
      { day: 17, title: 'Drive to Pokhara via Siwai',                                       description: '3-4 hours drive. Lakeside hotel celebration.' },
      { day: 18, title: 'Drive to Kathmandu (1,400 m)',                                     description: '7–8 hours. Tourist bus to Kathmandu Valley.' },
      { day: 19, title: 'Transfer to International Airport — Final Departure',              description: 'Final breakfast and airport transfer.' },
    ],
    ctaText: 'Tent Peak with ABC',
  },
};