import { TrekData } from './ExpeditionPage';

export const expeditions: Record<string, TrekData> = {
  'island-peak': {
    title: 'Island Peak Climbing',
    duration: '16 Days',
    difficulty: 'Challenging / Semi-Technical',
    elevation: '6,187 m / 20,293 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Climbing',
    accommodation: 'Tea House / Hotel & Base Camp (Mini Tented Village)',
    heroImages: ['/assets/images/island-peak.jpg', '/assets/images/island-peak-climb.jpg', '/assets/images/khumbu.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Island Peak Climbing', href: '#' },
    ],
    description: `The quintessential Himalayan climb: bridging the gap between trekking and true mountaineering in the shadow of the world's highest peaks. This 16-day Island Peak expedition follows the legendary Khumbu trail before a technical ascent of Imja Tse (6,187m).`,
    highlights: [
      'Summit Island Peak (Imja Tse) at 6,187m — a world-class mountaineering achievement',
      'Front-row seat to Lhotse (8,516m) — the world\'s fourth-highest mountain',
      'The "Island in a Sea of Ice" — dramatic glacial surroundings',
      'Spiritual heart of the Khumbu: Tengboche Monastery',
      'Explore Namche Bazaar, the vibrant Sherpa capital',
      'Authentic expedition camping at Island Peak Base Camp (5,240m)',
      'Glacier navigation and headwall challenge on the final ascent',
    ],
    overview: [
      `The Island Peak Climbing expedition (locally known as Imja Tse) is a premier mountaineering challenge that requires excellent physical stamina and a basic understanding of technical climbing skills. The journey begins with a thrilling flight to Lukla (2,846m) and follows the legendary trail through the Khumbu Valley before turning toward the trek's ultimate objective: the 6,189m summit of Island Peak.`,
      `Success on this peak depends on rigorous training emphasizing cardiovascular endurance and strength-building at least 3 to 4 months before departure. The terrain is diverse and demanding, moving from rocky scrambles to a steep snow-and-ice headwall requiring crampons, a harness, and fixed ropes. Required permits include the Sagarmatha National Park permit, the Khumbu Pasang Lhamu local permit, and the NMA climbing permit.`,
      `The expedition reaches its dramatic climax at the summit of Island Peak (6,189m), where climbers are rewarded with an intimate, panoramic view of the massive Lhotse South Wall, Ama Dablam, and Makalu. This is a profound immersion into the world of Himalayan climbing, connecting the bustling tea houses of the lower valley to the stark, silent majesty of the high glaciers.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances such as weather, flight delays, or health concerns may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                   description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner at a traditional Nepali restaurant.' },
      { day: 3,  title: 'Fly to Lukla (2,840 m) & Trek to Phakding (2,610 m)',              description: '35-minute flight or drive via Manthali/Ramechhap. Trek 3–4 hours.' },
      { day: 4,  title: 'Trek to Namche Bazaar (3,440 m)',                                   description: '5–6 hours through forests and suspension bridges.' },
      { day: 5,  title: 'Acclimatization Day at Namche Bazaar',                             description: 'Rest and acclimatization. Optional hike to Hotel Everest View (3,880m).' },
      { day: 6,  title: 'Trek to Tengboche Monastery (3,860 m)',                             description: '5–6 hours to the spiritual heart of the Khumbu.' },
      { day: 7,  title: 'Trek to Dingboche (4,410 m)',                                       description: '5–6 hours through increasingly alpine scenery.' },
      { day: 8,  title: 'Trek to Chukhung (4,730 m)',                                        description: '4–5 hours. Overnight at guesthouse.' },
      { day: 9,  title: 'Trek to Island Peak Base Camp (5,240 m)',                           description: '4–5 hours. Overnight at tented camp.' },
      { day: 10, title: 'Rest & Acclimatization Day at Base Camp',                          description: 'Equipment check and crampon practice.' },
      { day: 11, title: 'Summit Island Peak (6,187 m) & Return to Chukhung',                description: '9–10 hours. Early alpine start, summit push and descent.' },
      { day: 12, title: 'Trek to Tengboche (3,860 m)',                                       description: '6–7 hours descending through the Imja Valley.' },
      { day: 13, title: 'Trek to Namche Bazaar (3,440 m) via Khumjung',                     description: '5–6 hours. Return to the Sherpa capital.' },
      { day: 14, title: 'Trek to Lukla (2,840 m)',                                           description: '6–7 hours. Final trekking day.' },
      { day: 15, title: 'Fly Back to Kathmandu',                                             description: '35-minute flight or drive via Manthali/Ramechhap.' },
      { day: 16, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],
   
    ctaText: 'Island Peak',
  },

  'mera-peak': {
    title: 'Mera Peak Climbing',
    duration: '20 Days',
    difficulty: 'Challenging / Semi-Technical',
    elevation: '6,470 m / 21,227 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Climbing',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/mera-peak.jpg', '/assets/images/mera-summit.jpg', '/assets/images/hinku-valley.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Mera Peak Climbing', href: '#' },
    ],
    description: `A soaring journey to the ultimate Himalayan vantage point, where the summits of Everest, Lhotse, Makalu, Cho Oyu, and Kanchenjunga ignite in a single, breathtaking horizon. Nepal's highest trekking peak at 6,476m offers the finest panoramic view in the Himalayas.`,
    highlights: [
      "Summit Mera Peak (6,476m) — Nepal's highest trekking peak",
      'The "Big Five" panorama: Everest, Lhotse, Makalu, Cho Oyu, and Kanchenjunga simultaneously',
      'Trek through the remote and pristine Hinku Valley wilderness',
      'High camp experience at 5,800m before the summit push',
      'Authentic glacier traversal on a non-technical route',
      'Cross the dramatic Zatrwa La Pass (4,610m)',
      'Cultural immersion in remote Sherpa villages like Kothe and Tangnag',
    ],
    overview: [
      `The Mera Peak Climbing expedition stands as Nepal's highest trekking peak, requiring exceptional physical endurance and a high tolerance for cold. The journey begins with a flight to Lukla (2,846m) and quickly deviates into the remote Hinku Valley. A 18-to-20-day itinerary is essential, with strategic acclimatization days and a high camp at 5,800m before the final push.`,
      `Success depends on rigorous training focused on cardiovascular capacity and weighted hiking at least 4 months before departure. The extreme altitude and glacial terrain require double mountaineering boots, crampons, and a professional layering system. This expedition requires the Makalu Barun National Park permit and a specific Mera Peak climbing permit from the NMA.`,
      `The expedition reaches its breathtaking climax at the central summit of Mera Peak (6,476m), offering arguably the finest panoramic view in the Himalayas — five of the world's fourteen 8,000m peaks visible at once. The final leg follows a reflective trek back over the Zatrwa La Pass to Lukla.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early and booking international flights with buffer days.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner at a traditional Nepali restaurant.' },
      { day: 3,  title: 'Fly to Lukla (2,840 m) & Trek to Paiya / Chutok (2,800 m)',        description: '35-minute flight or drive via Manthali/Ramechhap. Trek 3–4 hours.' },
      { day: 4,  title: 'Trek to Pangkongma (2,900 m)',                                      description: '6–7 hours trekking.' },
      { day: 5,  title: 'Trek to Nashing Dingma (2,963 m)',                                  description: '6–7 hours through forest terrain.' },
      { day: 6,  title: 'Trek to Chholem Kharka (3,600 m)',                                  description: '6–7 hours. Entering high-altitude terrain.' },
      { day: 7,  title: 'Trek to Khola Kharka (4,270 m)',                                    description: '6–7 hours. Panoramic ridgeline walking.' },
      { day: 8,  title: 'Trek to Kothe (3,600 m)',                                           description: '6–7 hours descending into the Hinku Valley.' },
      { day: 9,  title: 'Trek to Tangnag (4,350 m)',                                         description: '6–7 hours deeper into the valley.' },
      { day: 10, title: 'Acclimatization & Rest Day at Tangnag',                            description: 'Rest and short acclimatization hike.' },
      { day: 11, title: 'Trek to Khare (4,900 m)',                                           description: '4–5 hours to the last guesthouse before the glacier.' },
      { day: 12, title: 'Acclimatization Day & Climbing Practice at Khare',                 description: 'Crampon and ice-axe practice. Rest and preparation.' },
      { day: 13, title: 'Trek to Mera High Camp (5,800 m)',                                  description: '7–8 hours. Overnight at tented camp.' },
      { day: 14, title: 'Summit Mera Peak (6,470 m) & Return to Khare',                     description: '10–15 hours. Early alpine start for summit, then descent.' },
      { day: 15, title: 'Spare / Weather Contingency Day',                                  description: 'Reserved for weather delays or used as a rest day anywhere on the route.' },
      { day: 16, title: 'Trek to Kothe (3,600 m)',                                           description: '6–7 hours descending.' },
      { day: 17, title: 'Trek to Thuli Kharka (4,200 m)',                                    description: '6–7 hours. Ascending back toward the pass.' },
      { day: 18, title: 'Trek to Lukla (2,840 m) via Zatrwa La Pass (4,610 m)',             description: '7–8 hours crossing the dramatic pass.' },
      { day: 19, title: 'Fly Back to Kathmandu',                                             description: '35-minute flight or drive via Manthali/Ramechhap.' },
      { day: 20, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],

    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials including documents, water, camera, and sunscreen.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Mera Peak',
  },

  'pisang-and-thorung-la': {
    title: 'Pisang Peak & Thorung La Pass',
    duration: '22 Days',
    difficulty: 'Strenuous / Semi-Technical',
    elevation: '6,091 m / 19,980 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Strenuous / Technical (Snow & Ice)',
    accommodation: 'Tea House / Hotel & Base Camp (Mini Tented Village)',
    heroImages: ['/assets/images/pisang-peak.jpg', '/assets/images/thorung-la.jpg', '/assets/images/annapurna-circuit.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Pisang Peak & Thorung La Pass', href: '#' },
    ],
    description: `Follow the Marsyangdi River to the stars, standing atop Pisang Peak for a bird's-eye view of the path that leads you over the world's most famous pass. This 22-day odyssey combines a technical 6,000m summit with the iconic Thorung La crossing.`,
    highlights: [
      'Summit Pisang Peak (6,091m) — a spectacular 360° panorama of the Annapurna range',
      'Cross Thorung La Pass (5,416m) — the world\'s most famous high-altitude mountain pass',
      'Trek beneath Paungda Danda — the 1,500m "Great Wall of Annapurna"',
      'Medieval Tibetan-influenced villages of Upper Pisang, Ngawal, and Braka',
      'High-altitude desert transition in the Manang rain-shadow zone',
      'Visit the 108 sacred springs of Muktinath temple',
      'Pass through Marpha — the apple capital of Nepal',
    ],
    overview: [
      `The Pisang Peak and Thorong La Pass expedition combines a challenging 6,000m summit with the world's most iconic mountain crossing. A 22-day itinerary is essential to facilitate a robust acclimatization profile, utilizing the initial trek through the Manang district to naturally build stamina for both the technical summit and the high-altitude pass crossing.`,
      `The terrain is exceptionally diverse, transitioning from lush rhododendron forests to the steep uniform snow slopes of Pisang Peak, requiring crampons, ice axes, and fixed ropes. This trek requires the NMA climbing permit for Pisang Peak, along with the ACAP permit and TIMS card.`,
      `The trek reaches its dual climaxes at the summit of Pisang Peak (6,091m) and the prayer-flag-strewn crest of Thorong La Pass (5,416m). From these vantage points, trekkers are rewarded with panoramas stretching from the Manaslu range to the immense Dhaulagiri Massif.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early and booking international flights with buffer days.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner at a traditional Nepali restaurant.' },
      { day: 3,  title: 'Drive to Syange (1,100 m)',                                         description: 'Private 4WD journey 7–8 hours.' },
      { day: 4,  title: 'Trek to Tal (1,700 m)',                                              description: '5–6 hours along the Marsyangdi River gorge.' },
      { day: 5,  title: 'Trek to Danaque (1,860 m)',                                         description: '5–6 hours through rhododendron forests.' },
      { day: 6,  title: 'Trek to Chame (2,670 m)',                                           description: '5–6 hours to the Manang district headquarters.' },
      { day: 7,  title: 'Trek to Pisang Village (3,300 m)',                                  description: '5–6 hours with stunning views of Annapurna II.' },
      { day: 8,  title: 'Acclimatization Day in Upper Pisang',                              description: 'Explore the village, monastery, and surrounding ridges.' },
      { day: 9,  title: 'Trek to Pisang Peak Base Camp (4,380 m)',                           description: '6–7 hours ascending to base camp. Tented camp.' },
      { day: 10, title: 'Move to High Camp (5,450 m)',                                       description: '6–7 hours. Overnight at tented camp.' },
      { day: 11, title: 'Acclimatization & Explore High Camp',                              description: 'Short exploration and preparation for summit day.' },
      { day: 12, title: 'Summit Pisang Peak (6,091 m) & Return to Base Camp',               description: '9–10 hours. Early alpine start, summit push and descent.' },
      { day: 13, title: 'Spare Day — Weather Contingency',                                  description: 'Reserved for bad weather or extra recovery.' },
      { day: 14, title: 'Trek to Pisang Village (3,300 m)',                                  description: '5–6 hours descending from base camp.' },
      { day: 15, title: 'Trek to Manang (3,540 m)',                                          description: '6–7 hours. Rejoin the Annapurna Circuit.' },
      { day: 16, title: 'Trek to Yak Kharka (4,050 m)',                                      description: '5–6 hours on the classic Annapurna route.' },
      { day: 17, title: 'Trek to Thorong Phedi (4,450 m)',                                   description: '5–6 hours. Final camp before the pass.' },
      { day: 18, title: 'Cross Thorong La Pass (5,416 m) & Descend to Muktinath (3,760 m)', description: '7–8 hours. The legendary pass crossing.' },
      { day: 19, title: 'Trek to Jomsom (2,720 m)',                                          description: '5–6 hours through the Kali Gandaki gorge.' },
      { day: 20, title: 'Morning Flight to Pokhara',                                         description: '30-minute scenic mountain flight.' },
      { day: 21, title: 'Drive to Kathmandu',                                                description: '7–8 hours by tourist bus.' },
      { day: 22, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials including documents, water, camera, and sunscreen.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Pisang Peak',
  },

  'pisang-peak': {
    title: 'Pisang Peak Climbing',
    duration: '15 Days',
    difficulty: 'Challenging / Semi-Technical',
    elevation: '6,091 m / 19,983 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Strenuous / Technical (Snow & Ice)',
    accommodation: 'Tea House / Hotel & Base Camp (Mini Tented Village)',
    heroImages: ['/assets/images/pisang-peak.jpg', '/assets/images/pisang-summit.jpg', '/assets/images/annapurna-view.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Pisang Peak Climbing', href: '#' },
    ],
    description: `Stand on a 6,000m pedestal for a rare, unobstructed perspective of Annapurna II, III, and IV, stretching across the horizon like a frozen wave. This focused 15-day Pisang Peak expedition combines a technical summit with classic Annapurna cultural immersion.`,
    highlights: [
      'Summit Pisang Peak (6,091m) — the iconic Pyramid Summit of the Annapurna region',
      'Bird\'s-eye panorama of the entire Annapurna Massif from the summit',
      'Upper Pisang cultural immersion in a medieval Tibetan-influenced village',
      'Cross Thorong La Pass (5,416m) — the world\'s most famous mountain pass',
      'Visit the sacred Muktinath Temple complex',
      'High-altitude desert landscapes of the Mustang rain shadow',
      'Scenic Jomsom mountain flight over the Kali Gandaki gorge',
    ],
    overview: [
      `The Pisang Peak Climbing expedition is widely considered one of the most accessible 6,000m summits in the Annapurna region. The journey follows the scenic Annapurna Circuit trail toward the 6,091m summit. A 15-day itinerary provides essential acclimatization days in the upper Manang Valley before the final ascent.`,
      `The final ascent involves a steep snow headwall of approximately 45–50 degrees, requiring crampons, an ice axe, and fixed ropes. This trek requires an NMA climbing permit, the ACAP permit, and a TIMS card.`,
      `The trek reaches its rewarding climax at the summit of Pisang Peak (6,091m), with a spectacular 360-degree panorama of the Damodar Himalaya and the Annapurna range, followed by the legendary Thorong La Pass (5,416m) and the sacred temples of Muktinath.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,350 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Kathmandu Preparation & Sightseeing',                              description: 'Half-day city tour, trek briefing, gear check. Welcome dinner.' },
      { day: 3,  title: 'Drive from Kathmandu to Dharapani (1,860 m)',                      description: '7–8 hours by private vehicle.' },
      { day: 4,  title: 'Trek from Dharapani to Chame (2,670 m)',                           description: '5–6 hours. Entering the Manang district.' },
      { day: 5,  title: 'Trek from Chame to Upper Pisang (3,300 m)',                        description: '5–6 hours with stunning views of Paungda Danda.' },
      { day: 6,  title: 'Acclimatization Day in Upper Pisang',                             description: 'Explore the medieval village and monastery.' },
      { day: 7,  title: 'Trek to Pisang Peak Base Camp (4,380 m)',                          description: '5–6 hours ascending to tented base camp.' },
      { day: 8,  title: 'Move to High Camp (5,400 m)',                                      description: '4–5 hours. Equipment check and preparation.' },
      { day: 9,  title: 'Summit Day — Pisang Peak (6,091 m) & Descend to Base Camp',        description: '9–10 hours. Early alpine start and full descent.' },
      { day: 10, title: 'Spare Day — Weather Contingency',                                 description: 'Reserved for bad weather. Used as rest day if conditions were clear.' },
      { day: 11, title: 'Trek from Base Camp to Manang (3,540 m)',                          description: '6–7 hours descending to the Annapurna Circuit.' },
      { day: 12, title: 'Trek from Manang to Yak Kharka (4,110 m)',                         description: '4–5 hours on the classic Annapurna route.' },
      { day: 13, title: 'Trek to Thorong Phedi (4,450 m)',                                  description: '3–4 hours. Final overnight before the pass.' },
      { day: 14, title: 'Cross Thorong La Pass (5,416 m) to Muktinath (3,760 m)',           description: '7–8 hours. The legendary pass crossing.' },
      { day: 15, title: 'Drive / Fly to Pokhara & Return to Kathmandu',                    description: '30-minute flight from Jomsom or drive.' },
      { day: 16, title: 'Transfer to International Airport — Final Departure',              description: 'Airport transfer for your onward journey.' },
    ],
    
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials including documents, water, camera, and sunscreen.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Pisang Peak',
  },

  'tharpu-chuli': {
    title: 'Tharpu Chuli (Tent Peak) with Annapurna Base Camp',
    duration: '19 Days',
    difficulty: 'Challenging / Alpine',
    elevation: '5,663 m / 18,580 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Climbing',
    accommodation: 'Tea House / Hotel & Base Camp (Mini Tented Village)',
    heroImages: ['/assets/images/tent-peak.jpg', '/assets/images/annapurna-base-camp.jpg', '/assets/images/poon-hill.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Tharpu Chuli with ABC', href: '#' },
    ],
    description: `Where Earth meets sky: trace the sacred trails of the Annapurna Sanctuary to a triumphant summit, where the wind whispers secrets of the giants that surround you. This 19-day expedition combines the legendary Annapurna Base Camp trek with the technical ascent of Tharpu Chuli (5,663m).`,
    highlights: [
      'Summit Tharpu Chuli / Tent Peak (5,663m) inside the Annapurna Sanctuary',
      'The 360° amphitheater view: Annapurna I (8,091m), Annapurna South, and sacred Machhapuchhre',
      'Stand at Annapurna Base Camp (4,130m) surrounded by the world\'s 10th highest peak',
      'Classic Poon Hill sunrise over the Dhaulagiri and Annapurna ranges',
      'Sacred Machhapuchhre (Fishtail) — the holy mountain that has never been summited',
      'Gurung cultural heritage through villages like Chhomrong',
      'Trek through some of Nepal\'s finest rhododendron forests',
      'Relax at Jhinu Danda natural hot springs after the descent',
    ],
    overview: [
      `The Tent Peak Climbing with Annapurna Base Camp expedition combines a trek into the heart of the Annapurna Sanctuary with a technical ascent of Tharpu Chuli (5,663m). The adventure begins through the rhododendron forests of the Modi Khola valley, passing Machhapuchhre Base Camp before reaching the natural amphitheater of Annapurna Base Camp (4,130m).`,
      `The ascent of Tent Peak involves navigating across a rubble-covered glacier and climbing steep snow slopes of 45–50 degrees, requiring crampons, an ice axe, and fixed ropes. This journey requires the ACAP permit, TIMS card, and a specific NMA climbing permit.`,
      `The expedition reaches its dramatic climax at the summit of Tent Peak (5,663m), with views of Annapurna South, Hiunchuli, and the fishtail peak of Machhapuchhre. The final leg descends to the natural hot springs of Jhinu Danda.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner at a traditional Nepali restaurant.' },
      { day: 3,  title: 'Drive to Pokhara (900 m) by Tourist Bus',                          description: '7–8 hours. Overnight at hotel.' },
      { day: 4,  title: 'Drive to Tikhedunga (1,540 m) & Trek to Ulleri (2,070 m)',         description: '3–4 hours drive, then 2–3 hours trekking.' },
      { day: 5,  title: 'Trek to Ghorepani (2,840 m)',                                       description: '5–6 hours through rhododendron forests.' },
      { day: 6,  title: 'Poon Hill Sunrise (3,210 m) & Trek to Tadapani (2,610 m)',         description: '1–2 hours sunrise hike, then 6–7 hours to Tadapani.' },
      { day: 7,  title: 'Trek to Chomrong (2,140 m)',                                        description: '5–6 hours. Gateway to the Annapurna Sanctuary.' },
      { day: 8,  title: 'Trek to Dovan (2,600 m)',                                           description: '5–6 hours through bamboo and rhododendron forests.' },
      { day: 9,  title: 'Trek to Deurali (3,230 m)',                                         description: '4–5 hours. Entering the upper sanctuary zone.' },
      { day: 10, title: 'Trek to Annapurna Base Camp (4,130 m)',                             description: '5–6 hours. Standing at the heart of the sanctuary.' },
      { day: 11, title: 'Trek to Tent Peak Base Camp (4,400 m)',                             description: '5–6 hours. Transition to tented camp.' },
      { day: 12, title: 'Move to High Camp (5,000 m approx.)',                              description: '3–4 hours. Final preparation before summit day.' },
      { day: 13, title: 'Summit Tent Peak (5,663 m) & Return to Base Camp',                 description: '9–10 hours. Early alpine start, summit push and descent.' },
      { day: 14, title: 'Trek to Deurali (3,230 m)',                                         description: '6–7 hours descending through the sanctuary.' },
      { day: 15, title: 'Trek to Chomrong (2,140 m)',                                        description: '6–7 hours. Stop at Jhinu Danda hot springs.' },
      { day: 16, title: 'Trek to Ghandruk (1,940 m)',                                        description: '5–6 hours through Gurung villages.' },
      { day: 17, title: 'Drive to Pokhara via Siwai in Lower Ghandruk',                     description: '3–4 hours by private vehicle.' },
      { day: 18, title: 'Drive to Kathmandu by Tourist Bus',                                 description: '7–8 hours. Overnight at hotel.' },
      { day: 19, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],
    
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials including documents, water, camera, and sunscreen.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'the Sanctuary',
  },

  'yala-peak': {
    title: 'Yala Peak Climbing',
    duration: '14 Days',
    difficulty: 'Challenging',
    elevation: '5,500 m / 18,044 ft',
    season: 'Spring (Mar–May) & Autumn (Sep–Nov)',
    groupSize: '2 or more',
    activity: 'Trekking / Climbing',
    accommodation: 'Tea House & Hotel',
    heroImages: ['/assets/images/yala-peak.jpg', '/assets/images/langtang-valley.jpg', '/assets/images/kyanjin-gompa.jpg'],
    breadcrumb: [
      { label: 'Nepal', href: '/Nepal' },
      { label: 'Expeditions', href: '/Nepal#expeditions' },
      { label: 'Yala Peak Climbing', href: '#' },
    ],
    description: `An ideal introduction to high-altitude climbing, where gentle snow slopes lead to a breathtaking vantage point over the wild landscapes of the Langtang Valley. This 14-day expedition through Langtang National Park culminates at the summit of Yala Peak (5,500m).`,
    highlights: [
      'Visit the resilient Langtang Village and the ancient Kyanjin Gompa monastery',
      'Panoramic mountain views from Tserko Ri — one of Nepal\'s finest viewpoints',
      'Summit Yala Peak (5,500m) — a perfect introduction to Himalayan mountaineering',
      'Visit the Kyanjin Gompa yak cheese factory',
      'Spectacular views of Shishapangma (the only 8,000m peak in Tibet) from the summit',
      'Trek through the dramatically recovered Langtang Valley',
      'Immerse in warm Tamang village culture along the trail',
    ],
    overview: [
      `The Yala Peak Climbing expedition is an ideal entry-level mountaineering experience. The journey begins with a scenic drive from Kathmandu to Syabrubesi (1,500m) and winds through the beautiful Langtang National Park toward the summit of Yala Peak at 5,520m. Strategic rest days in Kyanjin Gompa allow your body to adapt to the high-alpine environment.`,
      `The terrain transitions from lush rhododendron forests to rocky moraines and snow-covered slopes, requiring crampons and a versatile layering system. This trek requires the Langtang National Park entry permit and a TIMS card.`,
      `The trek reaches its rewarding climax at the summit of Yala Peak (5,520m), with a spectacular panorama of Shishapangma and the sprawling Ganesh Himal range. The final leg follows a reflective descent back through the valley.`,
      `NOTE: We strive to follow the planned itinerary, but unforeseen circumstances may require adjustments. We strongly recommend arriving one or two days early.`,
    ],
    itinerary: [
      { day: 1,  title: 'Arrival in Kathmandu (1,400 m)',                                    description: 'Airport pick-up and transportation to hotel.' },
      { day: 2,  title: 'Half-day city tour & trek briefing',                                description: 'Afternoon trek briefing. Welcome dinner at a traditional Nepali restaurant.' },
      { day: 3,  title: 'Drive to Syabru Besi (1,462 m) by Local Bus',                      description: '7–8 hours through scenic mountain roads.' },
      { day: 4,  title: 'Trek to Lama Hotel (2,500 m)',                                      description: '5–6 hours through dense forest.' },
      { day: 5,  title: 'Trek to Langtang Village (3,400 m)',                                description: '5–6 hours. Trail opens to wide alpine meadows.' },
      { day: 6,  title: 'Trek to Kyanjin Gompa (3,830 m)',                                   description: '4–5 hours to the spiritual heart of the Langtang region.' },
      { day: 7,  title: 'Kyanjin Gompa Exploration & Acclimatization Day',                  description: 'Optional hike to Tserko Ri (4,984m). Visit the yak cheese factory.' },
      { day: 8,  title: 'Trek to Yala Peak Base Camp (4,500 m)',                             description: '5–6 hours ascending to tented base camp.' },
      { day: 9,  title: 'Summit Yala Peak (5,500 m) & Return to Kyanjin Gompa',              description: '8–9 hours. Early alpine start, summit push and full descent.' },
      { day: 10, title: 'Spare Day — Weather Contingency',                                  description: 'Reserved for bad weather on summit day.' },
      { day: 11, title: 'Trek Back to Lama Hotel (2,500 m)',                                 description: '5–6 hours descending the Langtang Valley.' },
      { day: 12, title: 'Trek to Syabru Besi (1,462 m)',                                     description: '6–7 hours. Final trekking day.' },
      { day: 13, title: 'Drive Back to Kathmandu by Local Bus',                              description: '7–8 hours. Overnight at hotel.' },
      { day: 14, title: 'Transfer to International Airport — Final Departure',               description: 'Airport transfer for your onward journey.' },
    ],
    
    notes: [
      'One porter is assigned for every two trekkers, carrying a maximum of 25 kg / 55 lbs total.',
      'Each client duffel bag should weigh no more than 12.5 kg / 27.56 lbs.',
      'Bring a waterproof daypack for daily essentials including documents, water, camera, and sunscreen.',
      'Non-trekking luggage can be stored safely at your Kathmandu hotel.',
      'A high-quality hooded down jacket is included. USD 150 fee applies for loss or significant damage.',
      'A 4-season sleeping bag is included. USD 150 fee applies for loss or significant damage.',
    ],
    ctaText: 'Yala Peak',
  },
};